### ISSUE TITLE
[RFC] re-export the "get-meta-file" package

### ISSUE THREAD

**Issue by aleclarson** [mateodelnorte/meta#110]
To simplify plugin development, make `get-meta-file` an implementation detail and re-export it in the `meta` package.

```js
const getMetaFile = require('get-meta-file');
const { findConfig, readConfig } = require('meta');

assert(getMetaFile === readConfig);
assert(getMetaFile.getFileLocation === findConfig);
```

**Comment by mateodelnorte** [comment]
Not sure I agree with this one. It's going to make a bunch of circular dependencies. 

Can we quickly discuss what other type of functionality would be re-exported? What do we think a minimal api would look like to help people write good plugins?

**Comment by aleclarson** [comment]
They're not circular dependencies, because `meta` is loading these plugins _after_ the main module is initialized by the [bin/meta](https://github.com/mateodelnorte/meta/blob/master/bin/meta) module.

**Comment by mateodelnorte** [comment]
True, they're not ciruclar circular deps from npm's perspective.

**Comment by aleclarson** [comment]
The core plugins can move `meta` to their `peerDependencies`, I think.

**Comment by aleclarson** [comment]
> Can we quickly discuss what other type of functionality would be re-exported? What do we think a minimal api would look like to help people write good plugins?

Not sure. I haven't done much plugin writing yet. 

Configuration reading/writing is basically all we need. 😝

**Comment by mateodelnorte** [comment]
Hah. I'm cool with it. Let's just make sure we update docs to reflect it. We'll want to get something simple in there as a reminder for when we beef up and redo the docs, at large.

**Comment by mateodelnorte** [comment]
Note, you said writing, which is currently not one of the options we've noted. We'd need to write a set-meta-file or export something from `meta-project` for setting projects, and re-export get and set from `meta-configure`. And I think those would all start forming a pretty neat api together.

**Comment by aleclarson** [comment]
Bump. This would still be cool to have when someone gets time. :)
