### ISSUE TITLE
feature request - specify which repos to run an action on

### ISSUE THREAD

**Issue by plummer-flex** [mateodelnorte/meta#112]
In a meta repo I have instances where I want to commit code or run npm scripts on some but not all of the child repos.

Is there a way to specify which child repos a command should be run against?

```
meta -apply package-1 package-2 -command npm run docker-start
```

Is the designed behavior for projects that don't apply to the command fail or error? Or to navigate into the repos where the exclusive commands need to be run?

**Comment by patrickleet** [comment]
@mateodelnorte and I have been discussing a "tags" feature to make this easier but that's still just a discussion.

You can use multiple meta repositories for this, but we understand the need for less rigid solutions and on-the-fly inclusions/exclusions.

meta is built on top of loop, which does provide some capabilities for this. 

@mateodelnorte thoughts?

**Comment by plummer-flex** [comment]
@patrickleet I haven't played around with the plugin template.  From a high level design, would this we functionality that could be covered in a plugin?

**Comment by patrickmarabeas** [comment]
Is `meta npm run docker-start --include-only package-1,package-2` what you're after, or am I missing something?

**Comment by patrickleet** [comment]
that should do it, didn't realize that was exposed - I thought it might be cause I knew loop had it. My bad. @plummer-flex lmk if that solves your issue.
