### ISSUE TITLE
Feature request: can we remove the requirement for the meta folder to be a repo?

### ISSUE THREAD

**Issue by raghuramos1987** [mateodelnorte/meta#115]
I was wondering if the requirement for the meta folder to be a repo can be removed? I want to be able to use this locally and not have to share it with others specifically. Currently if I try to do this it works fine for the most part (i'm still a very new user) but I get an error for the meta repo saying its not a git repo which is annoying.

**Comment by mateodelnorte** [comment]
Why do you want to use `meta` without a parent meta-repo? You can easily use `loop` to do all of meta's commands against an arbitrary set of directories. 

Having a meta repo doesn't force you to share it. It will, for instance, at least make it easy for you to get everything in your codebase back exactly as it was when your laptop explodes or falls out a window.

**Comment by raghuramos1987** [comment]
hmmm... that makes sense. The only reason I was wondering about this is that I would have to create meta repos even though nobody else except me might be using them. Just more clutter. I guess I can always organize them into my own personal space. Thanks!
