### ISSUE TITLE
vscode usage with meta

### ISSUE THREAD

**Issue by wes1278** [mateodelnorte/meta#126]
Does anyone use vscode and meta? 

You cannot use the source control features of vscode if you've opened the meta project folder. That's because all the code that is being changed is inside a folder that's been gitignored (on purpose). 

@mateodelnorte @patrickleet any thoughts or workarounds come to mind?

for instance, let's say I have a meto repo called `supercool` and that's my meta repo. inside say I have `frontend` and a `backend` folders (both tied to some bitbucket repo).

if I open the `supercool` folder in vscode and start making changes, I cannot use the vscode built-in source control. However, if I opened the `frontend` folder in vscode, and started making changes, I'd be able to use the vscode git features. Is there a way to "trick" vscode or "trick" meta into doing what I want?

**Comment by patrickleet** [comment]
Yea vscode workspaces though it’s not perfect

**Comment by patrickleet** [comment]
Usually I just open multiple vscode instances for each project I’m currently working on, largely cause I use vscode debugger pretty heavily and I like have separate windows

**Comment by me-matt** [comment]
As a workaround, are you able to create a vs code workspace with the projects in?

You could store the workspace file in the meta repo.
