### ISSUE TITLE
Feature request - specify branch/sha/tag when adding new projects

### ISSUE THREAD

**Issue by ktmills** [mateodelnorte/meta#128]
This feature request goes beyond adding new projects.  It appears the .meta file doesn't store branch/sha/tag information and so always defaults to cloning origin/master at the HEAD.  Many of the projects I would like to add have on going development and changes are not always backwards compatible.  Therefore we want to lock down the branch/sha/tag of a project until someone has had the time to integrate a newer version of the repo, at which point the branch/sha/tag of that repo would be updated in the meta file.

**Comment by mateodelnorte** [comment]
Hi @ktmills. Not sure what you mean here. Branch, tag information for each child repo is maintained by git.

**Comment by ktmills** [comment]
for instance, when you run meta git clone <repo>, this will clone that top level repo, and then use the .meta file to clone all the repos that were added as children.  The cloning of a child repo leaves the repo at origin/master at the HEAD.   Its them up to the user to checkout a specific branch/tag/sha for that project repo.  For our work the origin/master branch at the HEAD might be incompatible with the current state of the parent repo.  An ideal solution for us would be to add branch/sha/tag information to the .meta file so that when meta git clone  is run, all child repo's are cloned and automatically set(git checkout) to point to the branch/sha/tag value in the .meta file.   

For example:

.meta file contents:

{
  "projects": {
      "project1": <repo url>
   }
  "versions": {
    "project1": <branch/sha/tag>
  }
}

meta git clone would essentially do the following:
git clone "projects::project1::<repo_url>" 
git checkout "versions::project1::<branch/sha/tag>"

For backwards compatibly, the version value would default to origin/master as it does today.

**Comment by mateodelnorte** [comment]
Meta doesn't support this now. Happy to accept a PR that would leverage one of the existing plugins to make it happen. Your easiest bet, however, is to just create a simple bash script call calls `meta git clone X` and then `cd`s into the pertinent child repos and changes their branch.

**Comment by ktmills** [comment]
Matt,
   I working on the feature request.  I'm completely new to node/javascript
but not new to coding.  I'm confused on the ternary operator used in some
of your argv parsing.

In meta-project-add for example:
const destArg = argv[2] === 'blank' ? argv[3] : argv[2]

I can't find anything on the internet about the comparison to 'blank'.
 Can you help me understand why this is needed and what 'blank' is.  My
only guess is it is a string containing the word "blank" but I can't
rectify in my mind why you would compare that to argv[2].

Thanks,
-Kelly

**Comment by niedfelj** [comment]
Would love this feature too. We rolled our own because we want the meta repo to be able to track separate branches on it's own branches, for building/deployment.

**Comment by mateodelnorte** [comment]
@ktmills I don't remember super clearly why the `== 'blank'` conditional is in there, but it may be that `commander.js` caused those values to equal `'blank'`. You could do some quick console.logs on the `program` variable to inspect and find out.

**Comment by mateodelnorte** [comment]
@ktmills What's the current status of your branches/PRs? What tasks do you have left in order to have things in working order?

**Comment by mateodelnorte** [comment]
One question I have overall is how you'll end up using this, in relation to `meta git checkout` commands. Do you not plan to use `meta git checkout` or `meta git branch`? Doing so would end up moving you off your default branches on any number of projects. You'd then need to remember which branches to move back to, when you're done with your feature branches. 

A `meta git checkout __default__` or something like it could get you back, but honestly, that's probably a good reason not to use non-master default branches.

**Comment by ktmills** [comment]
I plan on using it like submodules but with the ability to have some repo's
always on the latest by default.

**Comment by apapsch** [comment]
I have a concrete need for a functionality like this and I've got some time on my hands to do it.

> One question I have overall is how you'll end up using this, in relation to meta git checkout commands. Do you not plan to use meta git checkout or meta git branch? Doing so would end up moving you off your default branches on any number of projects. You'd then need to remember which branches to move back to, when you're done with your feature branches.

My use case is third party repositories. I want them in the meta repo for convenience and the third party uses non-standard branch names (no `master` branch). They are only minimally involved in the development workflow. No need for `meta git branch` or such things, though for the first iteration, I would just do:

* add an option to `meta project create` called `default-branch`, defaulting to `master`.
* record the information in `.meta`.
* respect the setting on clone (`meta project create` and `meta git update`).

**Comment by patrickleet** [comment]
sounds like a reasonable strategy, we'll be happy to take a look at a PR and see what you come up with.
