### ISSUE TITLE
How to write a plugin

### ISSUE THREAD

**Issue by drusellers** [mateodelnorte/meta#144]
Would it be possible to have a write up on building a plugin that doesn't include the tangent of writing a the plugin plugin, but simply uses it?

ref: https://medium.com/@patrickleet/developing-a-plugin-for-meta-bd2e9c39882d

**Comment by patrickleet** [comment]
yea that's pretty old - the project isn't even a meta plugin anymore, I separated it out.

The main advice I think still stands if you don't want to wait around - I'll copy and paste and reword things a bit below before we move into docs:

**Basic Setup**
1. Create a new repo for your plugin.

**Clone and set up meta for development**
```
npm i -g meta
meta git clone git@github.com:mateodelnorte/meta.git
cd ./meta
npm install
meta npm install
meta npm link --all
npm link
```

^ this will `meta git clone` the meta project, which is itself a meta repo, and install deps. It will then use `meta npm` to create links, which is the recommended way of developing npm modules locally.

now when you use `meta` it will be using meta from your cloned directory.

**Add your project to meta's .meta**
```
meta project add plugins/meta-xyz git@github.com:patrickleet/meta-xyz.git
```

**Add stuff to your plugin**
In the article I used this template: https://github.com/patrickleet/meta-template-meta-plugin - that should still work. To replace the variables you can just go through and do it manually, or use https://github.com/patrickleet/apply-template 

**link your plugin**
```
meta npm link --all
```

now `meta xyz` will be from your local version

**Comment by drusellers** [comment]
Awesome, I have it working now. Silly me, I was typing `meta npm link - all` rather than `meta npm link --all' 🤦‍♂

**Comment by mateodelnorte** [comment]
Woot

**Comment by patrickleet** [comment]
@drusellers that's cause medium's markdown editor converts them... 🙄I noticed only when I was copying it to you here. Need to update that...

**Comment by patrickleet** [comment]
fixed in the article.. :)

**Comment by drusellers** [comment]
awesome, thank you sir. :)
