### ISSUE TITLE
Possible "meta workflow" item

### ISSUE THREAD

**Issue by drusellers** [mateodelnorte/meta#146]
When working with a mix of repos and programming languages, how does the team see doing something like:

`meta yarn build` - builds front end code because it has a `package.json`

`meta cargo build` - builds backend api libraries

I understand I can do something like

`meta exec bin/build` as an abstraction that can then do what is ever right for the repo.  Just converting my project over to meta, and enjoying the mental model I'm building, now wondering how to have this scale for my various project tools.

Thank you.

**Comment by mateodelnorte** [comment]
You're going in the right direction. I often create a top level Makefile
with commands like `make install` that does `meta exec "make install"`,
which calls to a Makefile in each repo. If not all repos have one, I'll
pass a `--include only` or `--exclude` flag.

The benefit of the Makefile is that's it's self documenting. So now, every
dev gets every repo and every common command from one `meta git clone`.

**Comment by drusellers** [comment]
Thank you. :)

**Comment by patrickleet** [comment]
I have an internal quick little tool that scans all dirs for a package.json then returns a comma separated string of directories that match.

Then I can do `loop "echo 'command'" --include-only=$(find-node-directories)`

(meta uses loop under the hood)

I'll see if I can publish it and make it available - it's super unoptimized as well.. haha

**Comment by patrickleet** [comment]
though I'd recommend multiple meta repos before that probably - you can have meta repos within meta repos

```
- master-meta
   - node-projects-meta
   - cargo-projects-meta
```
