### ISSUE TITLE
Question: Experience with Code Editors + Ignored Files?

### ISSUE THREAD

**Issue by derks** [mateodelnorte/meta#152]
Hello, I just stumbled across Meta for the first and am trying it out as I'm in that typical mono-vs-multi repo situation.  I like the idea of meta, however upon trying it out I ran into an issue pretty quickly.  I use Atom, and like other code editors it supports the `.gitignore` file... so any directories or files that are ignored get grayed-out.  This is a big issue for me in that I now lost my indicators that colorize new (green) and modified (orange) files and the like.

I'm curious if others have worked around this somehow with Atom or similar code editors?  How do you use meta, but still maintain full git support being that the project folders are listed in the top level `.gitignore` file?

Thanks for the insight, I appreciate any feedback.

**Comment by mateodelnorte** [comment]
Haven't run into this problem, as I use VSCode. Perhaps there are some settings, to control the behavior. Don't know if Atom allows for extensions, but a meta extension could potentially make those not greyed out.

**Comment by derks** [comment]
@mateodelnorte thank you for the feedback. I switched over to VSCode, and though I sware without a doubt it initial *did* work... I am once again in the same spot I was with Atom.  Because the sub-project directories listed in `.gitignore` I lose all of my git colorization for modifications.

Would really appreciate anyone elses feedback here or is this just me?  Perhaps the workaround will be to add the sub-folders separately to the workspace. :/

FWIW, the pros outway the cons... and I've used it on two projects now.  So thank you for the work you are doing on this, it solves a real problem with a simple clean solution.

**Comment by patrickleet** [comment]
yea vscode workspaces - tbh I usually just open multiple vscodes cause I like having the full window integrated debugger for each that I'm working on

**Comment by derks** [comment]
@patrickleet I actually tried that. I had a workspace for the meta repo, and a separate that just included the sub-directory projects...  VSCode must be sourcing `.gitignore` all the way up the parent directory stack becasue if in that case it was still treating the subdirectories as ignored.  I'm at a loss here.

VSCODE: 1.34.0
macOS: Mojave 10.14.4
