### ISSUE TITLE
 Cannot seem to run meta when not a global module

### ISSUE THREAD

**Issue by nlubin-lv** [mateodelnorte/meta#17]
When trying to run meta from local npm modules you get this:

```
git:(meta)$ ./node_modules/.bin/meta
{ Error: ENOENT: no such file or directory, scandir '/projectName/node_modules/meta/node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at module.exports.error (/projectName/node_modules/meta/lib/listDirectories.js:32:28)
    at Object.<anonymous> (/projectName/node_modules/meta/bin/meta:13:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/projectName/node_modules/meta/node_modules' }
```

Is there anything that could be done about that or it has to be run globally?

Same thing happens if you run `meta` out of an npm package script.

**Comment by mateodelnorte** [comment]
What's your use case? Do you have a meta repo of meta repos?

**Comment by nlubin-lv** [comment]
I want for people to just be able to do npm install and for post install to do some meta stuff.

**Comment by nlubin-lv** [comment]
It seems to work fine when I git clone this repo and do a meta link to it.

The npm repo seems to have the issue.

**Comment by mateodelnorte** [comment]
Stuck at a client with low-to-no reception on my cel and no guest network connectivity. Is that the same error message you get when you execute from an npm script? 

So, it seems like meta should detect if it's installed globally or as a dependency of another project. Can you try manually commenting this out and seeing if things run? https://github.com/mateodelnorte/meta/blob/master/lib/listDirectories.js#L30-L38

BTW, if you run with `DEBUG="*"` before your command, you'll get all sorts of additional logging.

**Comment by mateodelnorte** [comment]
You'll need a little more tweaking than just commenting out the above. Basically, do a little work to make it skip the global modules, and see if that gets things going. If so, I can do some work later to have it check whether it's globally installed. Also happy to field PRs. :smile:

**Comment by nlubin-lv** [comment]
Is this only meant to work if globally installed though?

**Comment by mateodelnorte** [comment]
That was the original intention, but I have no qualms updating it to run from within another project/repo. I've had others ask me about support for meta repos in meta repos, but I think they use the globally installed executable.

**Comment by nlubin-lv** [comment]
I think you are a little confused as to the use.

This is a meta repo, I just want to set up a bunch of npm scripts that uses meta, but I dont want to require the people who use the repo to install meta globally -- just to have them as dependencies of the project.

**Comment by nlubin-lv** [comment]
Maybe I am mistaken onto how to use it?

**Comment by mateodelnorte** [comment]
Ah. Gotcha. Yea, generally, you're using meta as a globally installed tool. If you have a meta repo, with a `.meta` file in it, you would `npm i -g meta` and then `meta git clone [my repo url].git`. That would then clone your meta and child repos. 

From there, you have access to all the default meta plugins `meta git status`, etc. Or, you could `npm i --save-dev meta-yarn` and have access to the yarn plugin. Same with `npm i --save-dev meta-gh` and viewing issues and prs for your projects. 

That said, I'm not against people using it in the way you describe.

**Comment by mateodelnorte** [comment]
Btw, the docs totally suck right now, so thanks for plowing through it. I intend on creating some asciinema vids for all sorts of common usages and to put them on a gh-pages branch soon.

**Comment by allain** [comment]
Pretty sure this is resolved by the last commit.

**Comment by mateodelnorte** [comment]
Sounds right. ;) Cheers.
