### ISSUE TITLE
Can we convert the es6 to es5?

### ISSUE THREAD

**Issue by nlubin-lv** [mateodelnorte/meta#18]
Can we babelify meta (or buble or something) to make the es6 code into es5 for library -- otherwise the lib doesnt work for older versions of node.

**Comment by mateodelnorte** [comment]
Sure! Wanna take a PR swack at any one of the repos and I'll convert the rest?

**Comment by aleclarson** [comment]
I don't see the point in supporting old versions of `node` for a package admin CLI tool.

**Comment by mateodelnorte** [comment]
it makes sense, in its current form. if you're using `nvm` or `n`, you're going to pop over to that version and `npm i -g meta`. that's going to put it in the node_modules folder for that specific version, and if that version doesn't support const – or whatever – it's gonna blow up. 

That said, I think we can fix all of this by finding a nice way to use something like [pkg](https://github.com/zeit/pkg) to package things up in a way that won't even require node and npm to be installed. Then, we can just instruct people to install by `curl https://someurl-to-meta-installer.sh | sh`.
