### ISSUE TITLE
GUI support

### ISSUE THREAD

**Issue by kimsey0** [mateodelnorte/meta#186]
Are there any graphical tools that support meta yet? Are there plans to try to convince GUI client developers to support it?

(Issue search keywords: SourceTree, GitHub Desktop, TortoiseGit, Git Extensions, GitKraken, SmartGit, Tower, GitEye, Sublime Merge.)

**Comment by mateodelnorte** [comment]
I think we'd have a better time of creating a GUI for ourselves. Want to start off something very simple, using Electron?

**Comment by kimsey0** [comment]
I don't think I have the time to do a project like that justice at the moment. Maybe in the future, or if someone else ends up starting a project like that, where I can contribute. 😄

**Comment by thommelutten** [comment]
Opening this again due to personal interest. Have you heard of any newly started GUI-related projects that uses meta?

**Comment by kimsey0** [comment]
I have still not heard of any GUI's that use meta.

**Comment by patrickleet** [comment]
You could create a visual studio workspace consisting of all the projects in the meta repo, then use VS Code's gui.

At the root of your meta repo, create **yourprojectname.code-workspace**:
```
{
        "folders": [
                {
                        "path": "project-1"
                },
                {
                        "path": "project-2"
                },
                {
                        "path": "project-3"
                }
        ],
        "settings": {}
}
```

Then you can open that with `code`:

```
code ~/dev/project/yourprojectname.code-workspace
```

On top of their git GUI for multiple projects, you also can use the integrated debugger with multiple projects.

**Comment by kimsey0** [comment]
@patrickleet: I assume that would then be a setting for the meta repository to have meta create and keep that workspace file updated with new sub-repositories?

**Comment by patrickleet** [comment]
seems like the path of least resistance - it's interesting that it is a json file also - it's not too dissimilar to a meta file 

@mateodelnorte maybe a setting to use or the ability to understand VS Code Workspace file format for meta then just symlinking it?

I kinda like the idea of a settings option as well - could use that to create groups and just translate those to `include-only` for #234
