### ISSUE TITLE
meta git tag -a v0.0.x -m "tag message" fails

### ISSUE THREAD

**Issue by knutster** [mateodelnorte/meta#188]
## 🐛 Bug Report

running meta git tag -a v.0.0.x -m "tag message" fails for tag messages with whitespace.

This works for commits, but not tagging.

Explaining via pseudo code, the following happens:

for repo in repos:
  git tag -a v0.0.x -m tag message

ie. "tag message" is interpreted as 2 parameters, tag and message.

It works fine if the -m argument has no whitespace.

## To Reproduce

meta git tag -a v.0.0.x -m "tag message"

## Expected behavior

All repos are tagged with the same tag message.

**Comment by patrickleet** [comment]
as a workaround, `meta exec "command"` might work for you

`meta exec "git tag -a v.0.0.x -m 'tag message'"`
