### ISSUE TITLE
Support for bash-completion

### ISSUE THREAD

**Issue by udayshnk** [mateodelnorte/meta#192]
bash-completion auto complete feature would be really helpful. As an example if we type "meta git" and press tab, it would be nice to see options like pull, push, log, status.

**Comment by mateodelnorte** [comment]
Want to create a PR or recommend an approach? PR much preferred.

**Comment by udayshnk** [comment]
sure @mateodelnorte, will work on it

**Comment by MathieuSchopfer** [comment]
That would be really nice to have. Do you intend to also provide auto-completion of projects name ? (e.g. to use after `--include-only` directive)
