### ISSUE TITLE
Install failed on Opensuse Leap 15.1

### ISSUE THREAD

**Issue by enfoqueNativo** [mateodelnorte/meta#193]
## 🐛 Bug Report

Global install procedure via npm failed while cloning dependencies.

## To Reproduce

Issue "npm i -g meta" as root user (normal user doesn't have access to /usr/local/lib)

## Expected behavior

meta installed globally on the system

[2019-10-02T21_03_19_342Z-debug.log](https://github.com/mateodelnorte/meta/files/3683436/2019-10-02T21_03_19_342Z-debug.log)

**Comment by mateodelnorte** [comment]
Looks like a problem with your installation of `npm`, to me. 

```
41 silly fetchPackageMetaData fatal: no se pudo crear directorios principales de '/root/.npm/_cacache/tmp/git-clone-34fe79bf/.git'
...
44 verbose stack fatal: no se pudo crear directorios principales de '/root/.npm/_cacache/tmp/git-clone-34fe79bf/.git'```

It's attempting to install into /root.
