### ISSUE TITLE
What is the difference between "meta project create" and "meta project import"?

### ISSUE THREAD

**Issue by RobBednark** [mateodelnorte/meta#195]

**Comment by RobBednark** [comment]
I searched through the existing README and through the issues but didn't see anything describing how they differ.

**Comment by patrickleet** [comment]
`meta project import` will add an existing project to your .meta file and clone it

`meta project create` will add a new directory and git initialize it, and add the given remote

**Comment by RobBednark** [comment]
Thank you!  👍
