### ISSUE TITLE
Provide a way to not modify GIT ignore file

### ISSUE THREAD

**Issue by raypatterson** [mateodelnorte/meta#198]
## 🚀 Feature Proposal

Provide a configuration option to disable adding repo folder locations pattern to the `.gitignore` file.

## Motivation

When using the tool in a repo that has branches with different sub-repos, where repos are cleaned up and (re)installed when switching branches, the `.gitignore` accumulates duplicate patterns. Also, if install folders change, outdated ignore patterns persist. 

I understand this is satisfying an atypical use case, but I find it easier to import everything one folder (`repos`) and just ignore that.

E.g.

```shell
repos
├── repo-a
├── repo-b
├── collection-of-repos
└── another-collection-of-repos
```

## Example

`meta project import --no-ignore [folder] [repo url]`

**Comment by patrickleet** [comment]
`meta project migrate` adds things to .meta but not .gitignore... but that's for a different purpose - don't see how a flag could hurt.

@mateodelnorte thoughts?
