### ISSUE TITLE
crash when trying to see git status. 

### ISSUE THREAD

**Issue by bl1mp** [mateodelnorte/meta#199]
## 🐛 Bug Report
[Process:               meta [5706]
Path:                  /Applications/meta.app/Contents/MacOS/meta
Identifier:            meta.Mac
Version:               106 (106)
App Item ID:           1454769178
App External ID:       830625325
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           meta [5706]]
(A clear and concise description of what the bug is.)
App crashes when clicking on git status
## To Reproduce
click on status tab
just clicking on status will make it crash every time on my end (Catalina 10.15.2.)
## Expected behavior
should show status.
(A clear and concise description of what you expected to happen.)
information showing up about git status of current repo, instead it instantly crashes.

**Comment by mateodelnorte** [comment]
This library does not have a user interface. Where are you running this?

**Comment by bl1mp** [comment]
users/home directory/

:/

**Comment by patrickleet** [comment]
you install meta with `npm install -g meta` 

not sure what you have installed @bl1mp but it doesn't seem like this meta..

where'd you find it?
