### ISSUE TITLE
meta git push

### ISSUE THREAD

**Issue by adam-delaney** [mateodelnorte/meta#200]
Thank you for creating and maintaining this project it has been helpful with managing our numerous Github repos. We have found that when we run `meta git push` that meta will push empty branches. Is there a way to prevent this behavior if there are no code changes for that repo? Thanks in advance.

**Comment by mateodelnorte** [comment]
When you say empty branches, do you mean new branches with no changes? 

Effectively, `meta` is doing what you're telling it to `git push` in each repo. You can do a quick `meta git status` to make sure all projects are on the branches you want them to be, before doing your `mega git push`. You can also specifically tell meta to run only on certain repos with `--include-only repo-1, repo-2` or  `--exclude repo-1, repo-2`.
