### ISSUE TITLE
Recursive cloning (covering nested meta repos)

### ISSUE THREAD

**Issue by szero2one** [mateodelnorte/meta#203]
## 🚀 Feature Proposal

`meta git clone <project>` currently clones a single layer in. If you have a meta-repo within a meta-repo, it will only clone the direct children of the root meta repo. Would be great if it automatically detected sub meta repos, and performed the clone all the way down the subtrees. 

## Motivation

Practical experience. Would be convenient.

## Example

`meta git clone <project>` - clones everything.

**Comment by szero2one** [comment]
On a second thought, the only thing needed here may be an addition to the docs. Especially if the feature would be cumbersome to implement.

You can totally get by without nested meta-repos, but likely more people will run into this issue, so I added a [PR](https://github.com/mateodelnorte/meta/pull/205).

**Comment by mateodelnorte** [comment]
This would be fairly easy to implement in `meta-git-clone`. You would just have to detect the presence of a `.meta` file in a newly cloned repo. Happy to field a PR if someone wants to make it.

**Comment by patrickleet** [comment]
I take advantage of it not being recursive by default - if anything it should be a flag

**Comment by mateodelnorte** [comment]
I would assume it would be a flag.
