### ISSUE TITLE
Failed to switch to another branch in sub folder

### ISSUE THREAD

**Issue by zhouhao27** [mateodelnorte/meta#208]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

## To Reproduce

1. Add the repo (config) to project
```
meta project add apps/lark https://github.com/xxx/config
```

2. Try to switch to different branch in newly added project

```
git checkout config
```

Get the following error message:

> error: pathspec 'config' did not match any file(s) known to git

## Expected behavior

(A clear and concise description of what you expected to happen.)

**Comment by mateodelnorte** [comment]
Did you type `git checkout config` or `meta git checkout config`? Does the config branch exist in the repo?

**Comment by zhouhao27** [comment]
The branch exists in the repo because I can checkout in the folder other that the one created by `meta`. 

I'm using `git checkout config` because I don't want to checkout the whole project to this branch. Is this possible? Thanks.

**Comment by mateodelnorte** [comment]
You can, but that's not using meta.

**Comment by zhouhao27** [comment]
I fixed the issue. I think it's not the problem of `meta`. I accidentally add my subproject to main repository. Thanks.
