### ISSUE TITLE
Update multiple repositories at once

### ISSUE THREAD

**Issue by sneko** [mateodelnorte/meta#209]
_Cannot access the Gitter... 404 error_

Hi @mateodelnorte ,

Let's say I have 20 repositories, and 1 common to all others (for some helpers... like a library). Sometimes I make an important change and I want this one to be deployed as soon as possible.

I think I could hack something with meta except I cannot apply some filters on which repo to apply the steps.

While thinking about it I should first:
- Check all my repos are synchronized with remote for the wanted branch (if not, stop... since it would imply a lot of unwanted merges)
- Stash every current modifications
- Run a command to update my common library on all repositories (it would depend on langage and package manager...)
- Commit on all repositories with the same message
- Push on all repositories
- Unstash on all repositories

What do you think?

Maybe do you know some examples out there? Because for an "important" change, doing it manually is... very long and I could miss one repo.

Thank you,

**Comment by patrickleet** [comment]
we typically set up semantic-release and something like renovate bot, so once you publish the new shared lib, PRs are automatically made to all the other repos, and if you have good coverage/tests, turn on automerge.
