### ISSUE TITLE
Any way to clone only the subrepositories?

### ISSUE THREAD

**Issue by amir-abdi** [mateodelnorte/meta#210]
## 🤓 Question

Seems like the following workflow is not implemented.

    git clone https://user:pass@gitlab.example.com/myrepo 
    cd myrepo
    meta git clone https://user:pass@gitlab.example.com/myrepo .

With the last command, I only want to clone the sub-repositories into their respective directories.
Any solutions?

**Comment by mateodelnorte** [comment]
I can't see the contents of your top level repo but I assume it's a meta repo. If that's the case, just type `meta git update`.
