### ISSUE TITLE
Support for Git aliases

### ISSUE THREAD

**Issue by ojizero** [mateodelnorte/meta#211]
## 🚀 Feature Proposal

Add support to Git aliases, and other Git features that are missing from `meta-git`.

## Motivation

Some people (not sure how many but I'm one of them 😅) use Git aliases to ease up and speed up their development flow, by pretty much reimplementing the Git commands as done in `meta-git` we are missing this feature as we have to explicitly use the command that are redefined here.

This would also have the side effect of future proofing the package as we won't need to do anything to support any newer Git commands.

## Example

If for example you have the following in your `~/.gitconfig` file

```ini
[aliases]
    a = add
```

You should be able to run `meta git a` instead of `meta git add`.

This also goes for other more complex aliases that could be placed.

**Comment by ojizero** [comment]
@mateodelnorte a suggested way to implement this is to drop all the sub `meta-git` commands and have one command that just passes all arguments to Git as is and let Git handle everything from there.

**Comment by mateodelnorte** [comment]
I'd be happy to field a PR for it. Note we'll still need to support `meta
git update`

**Comment by ojizero** [comment]
alright I'll be checking it probably this weekend, I don't think it should be that complex implementing it while maintaining support for `meta git update` 🤔

**Comment by ojizero** [comment]
@mateodelnorte quick question 😬 does the `meta git update` command make sense to be a subcommand of `meta git` instead of directly be a child of `meta ? Since it's a command involving a concept needed for `meta` not `git` ? 🤔

**Comment by mateodelnorte** [comment]
Interesting point. It's probably semantics.

What would sound better to you? `meta update`, `meta project update`?

**Comment by ojizero** [comment]
I think `meta project update` would sound better 🤔 it'll also be more inline with other `meta project` child commands

**Comment by ojizero** [comment]
@mateodelnorte should we maintain `meta git update` and emit a deprecation warning or should just mark this as a breaking change and make it a major release 🤔

**Comment by mateodelnorte** [comment]
How about `meta project sync`? Would be nice to have it also notify of folders that are no longer tracked and provide a command to remove them.

I think a deprecation warning is good for now.

**Comment by ojizero** [comment]
hmmm that's actually even better 🤔 alright then I'll make it `meta project sync` and have it cleanup no longer needed child repos, and keep `meta git update` for the time being but have it emit a warning

**Comment by mateodelnorte** [comment]
I think it should just print out the commands a user can run to cleanup their workspace. I don't think it should do anything destructive on the fs.
