### ISSUE TITLE
Error codes aren't passed from Git subcommand

### ISSUE THREAD

**Issue by ojizero** [mateodelnorte/meta#212]
## 🐛 Bug Report

When `meta-git` fails it doesn't seem to pass the error code back.

## To Reproduce

- Run any invalid Git command `meta git blah blah` for example.

## Expected behavior

Should pass the error back, instead it does nothing.

Current behavior:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/14054961/73756822-e01b0d80-4770-11ea-93dd-cc9c85127220.png">

Expected behavior would be something like:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/14054961/73756916-0771da80-4771-11ea-8444-6dcd3507d764.png">

**Comment by mateodelnorte** [comment]
Thanks for catching. Interest in making a PR?

**Comment by ojizero** [comment]
yea sure thing :D I'll check this weekend along with #211 and probably make a single PR for both if that's ok 😬

**Comment by mateodelnorte** [comment]
Sounds great!

**Comment by ojizero** [comment]
@mateodelnorte just noticed that adding the `--exit-on-error` flag would cause meta to exit on failure and correct this behavior 🤔 unsure if this should e changed to be the default behavior but I think this could be marked as expected behavior if the flag is meant to be off by default 🤔

**Comment by mateodelnorte** [comment]
So, this is all inherited from `loop`. I think what we actually want is to make `--exist-on-aggregated-error` the default. That way, it will run through all command and exit code 1 if any of the child commands errored. 

https://github.com/mateodelnorte/loop/blob/311de8536bcb73e053ea29b74f62461588de48b7/bin/loop#L63

https://github.com/mateodelnorte/loop/blob/03047f3a430bd19fda61b6407374e8bc662fdf14/lib/loop.js#L22

**Comment by ojizero** [comment]
@mateodelnorte yea I did get to those files 😅 hmmm yea we could have that option be the default, do think it should be the default for all meta sub commands or only for Git, also wouldn't this constitute a breaking change ? as we are changing the old external behavior of the CLI

**Comment by mateodelnorte** [comment]
I think it should be the default for all. Let's get the PR up and play with it, and we can decide whether it will be breaking or not.

**Comment by ojizero** [comment]
@mateodelnorte there could be a downside for setting exit on aggregated error on all subcommands 🤔 say you only have a set of changes on some of the child repos and you wanna commit them, then there would be multiple errors on all child repos that don't have any change them (since Git doesn't like it)

Would it be reasonable to assume in such case the usage would have either exclude or include flags set? Or should the command be aware enough not to run in these child repos 🤔

**Comment by mateodelnorte** [comment]
And thus we arrive at why it's currently not the default. 😉

Personally, I'm fine leaving things as is and letting people writing
scripts add the extra flags when error codes are required.

**Comment by mateodelnorte** [comment]
Looks like ya gave the thumbs up on this one, so I'm gonna close for now. Re-open if you would like to continue the discussion.
