### ISSUE TITLE
`meta nonexistentcommand` does not display an error message nor does it exit with non zero status code

### ISSUE THREAD

**Issue by aalexgabi** [mateodelnorte/meta#214]
## 🐛 Bug Report

`meta nonexistentcommand` does not display an error message nor does it exit with non 0 status code

## To Reproduce

```
% meta nonexistentcommand
% echo $? 
0
```
## Expected behavior

To display an error and exit with an non zero status code

**Comment by mateodelnorte** [comment]
Would you like to make a PR for this?
