### ISSUE TITLE
`meta loop echo hi` does not echo hi

### ISSUE THREAD

**Issue by aalexgabi** [mateodelnorte/meta#215]
## 🐛 Bug Report

meta loop arguments are not passed to command without passing command as one argument

## To Reproduce

```
% meta loop echo hi
# Only displays folder names but not hi
```

## Expected behavior

Every argument passed to `meta loop command` should be passed to to the command.

**Comment by mateodelnorte** [comment]
`meta loop` is not a command. 

`meta exec echo hi` is a valid command

`loop echo hi` is a valid command, for `loop`.
