### ISSUE TITLE
meta git clone [directory] does not seem to work

### ISSUE THREAD

**Issue by smileatom** [mateodelnorte/meta#216]
## 🐛 Bug Report

I want git clone to work just as it does with regular repos when using meta git clone.
But if I specify the directory to clone to with meta git clone it is ignored and creates a dir for the repo name.

**Comment by patrickleet** [comment]
Do you mean `meta git clone <repoUrl> <directory>` ?

Can you include the exact commands you are running?

**Comment by smileatom** [comment]
yep thats the one

**Comment by mateodelnorte** [comment]
@smileatom would you like to make a pull request against https://github.com/mateodelnorte/meta-git/blob/master/bin/meta-git-clone to support the behavior? Looks like it is a relatively simple change.

**Comment by smileatom** [comment]
sure Ill look at it tomorrow

**Comment by smileatom** [comment]
sorry cornoavirus
