### ISSUE TITLE
meta does not install properly

### ISSUE THREAD

**Issue by amir-abdi** [mateodelnorte/meta#217]
## 🐛 Bug Report
Any meta command (e.g. `meta init`) will throw this error:
```
[SyntaxError: Unexpected token {]
```

## To Reproduce

Fresh install on Ubuntu 16.04 with the following commands:
```
sudo apt-get install nodejs
sudo apt-get install npm
sudo npm i -g meta
git init
meta init
```

**Comment by mateodelnorte** [comment]
Should you be using `npm i -g meta` without sudo instead? Sudo will install meta under root.

**Comment by amir-abdi** [comment]
I switched to Ubuntu 18.04, and the problem was surprisingly resolved. 

Without sudo, the installation throws a write permission error.

**Comment by mateodelnorte** [comment]
This is a linux file permissions issue regarding npm/node installation.
