### ISSUE TITLE
allow relative paths in meta loop 

### ISSUE THREAD

**Issue by smileatom** [mateodelnorte/meta#218]
## 🚀 Feature Proposal

(A clear and concise description of what the feature is.)
if I want to run a node command pointing to a javascript file I have to use the fully qualified path when I issue: meta loop "node /some/fully/qualified/path", it would be nice if one - I didnt have to quote the thing at all and two if relative paths could be used and have the plugin sort out the diff in the relative path from where the target repo is so that the node command wont fail when changing directories. 

## Motivation
Simply more useful.  The whole point of this tool is to be able to run command over multiple dirs.  So this would make it much simpler to use rather than just passing the whole quoted cmd line to commander or whatever.

## Example
Say I have a scripts dir in one of my repos I want to run against all repos.

I would like to be able to say meta loop node ./bin/scripts/dosomething.js, 
Rather than meta loop "node /Users/foo/long path to js file" since the script path is not relative to my other projects paths

**Comment by mateodelnorte** [comment]
This is not the case. meta-loop runs with the cwd set to the child repo's directory. Run `meta loop pwd` to illustrate.

**Comment by smileatom** [comment]
I will retest
