### ISSUE TITLE
Allow subsets of dirs to be created and added to project for reference by loop

### ISSUE THREAD

**Issue by smileatom** [mateodelnorte/meta#219]
## 🚀 Feature Proposal
Edited to remove include-only suggestion didnt realize loop had that already.
## Motivation
Allow me to create subsets of the meta repo and target them on the command line

## Example
1)  Create a defined subset that can be used forever more (it should be added to the .meta project)
meta -subset services /apis/services/*   <recursively adds all projects below services to a subset named "services"
The benefit to this is while YES I may create meta views on the overall project, if I force that on developers then each view is going to have to have it own path relative content aware type scripts.  It woud be easier to use subsets.

**Comment by mateodelnorte** [comment]
This exists. All options available to loop are available to meta. See:
https://github.com/mateodelnorte/loop#loop

**Comment by mateodelnorte** [comment]
"keys" for groups of repos has come up as a suggestion in the past. Would be happy to field a PR for this and gather the specs and conversation here.
