### ISSUE TITLE
Allow for STOP on failure of a looped command

### ISSUE THREAD

**Issue by smileatom** [mateodelnorte/meta#220]
## 🚀 Feature Proposal
While its great that command that dont apply CAN just fail in directories when they dont find files or something and just move on to the next repo in the list, in a large meta repo say 10-30-50 repo or more, you would have to be crazy to run such a thing.

An option to "stop looping", or stop the overall execution if ANY failure occurs in an execution on a repo should be provided.

## Motivation
Allow the command to stop before it potentially does damage if its not supposed to ever fail.

## Example
meta loop --stop-on-error "node foo.js"

**Comment by mateodelnorte** [comment]
This exists, however loop could use an update to documentation. Meta probably could, too. 

https://github.com/mateodelnorte/loop/blob/311de8536bcb73e053ea29b74f62461588de48b7/bin/loop#L62
