### ISSUE TITLE
Version Not Set in Source Files

### ISSUE THREAD

**Issue by apeschel** [mateodelnorte/meta#221]
## 🐛 Bug Report

A fairly minor bug -- the version is not being set in the package.json for the source blobs available on the releases page.

The reason seems pretty simple -- the version for this repo is being managed with git tags, and semantic-release is setting the version prior to publishing.

However, the source blobs do not contain the git repository, nor the git tags associated with the version.

Perhaps something to set the correct version in the source blobs before they are published to github? 

## To Reproduce

1. Download and extract the tar gunzip or zip containing the source.
2. Run npm install against the directory
3. Check the version with `meta --version` -- it will show "0.0.0-development"

## Expected behavior

Accurate version information of the application should be shown.

**Comment by mateodelnorte** [comment]
Install meta via `npm install -g meta`. This will give you a version with these values populated. Local installation is for development of these packages only. 

If you've got some other reason for installing using unusual methods, feel free to let us know.

**Comment by apeschel** [comment]
@mateodelnorte The source blobs are useful when using a packaging system other than npm -- in my specific case, homebrew.

**Comment by mateodelnorte** [comment]
Why would you use Homebrew to install an npm package? Sounds like an unsupported use case to me.

Source files with a version number are available in any tarball from npm. Can you not just download the tarball from npm, untar, and install via your custom brew formula?

**Comment by mateodelnorte** [comment]
Maybe you can fill me in on how you're packaging meta for instal via homebrew, and why you'd want to. My initial question is how its dependency on node and npm are handled.

**Comment by apeschel** [comment]
@mateodelnorte Here's Formula I put together: https://github.com/apeschel/homebrew-core/blob/new_formula/meta-git/Formula/meta-git.rb

As for the why - same reasons you would ever use an OS packager and not a language packer to distribute your application, I suppose.

npm works fine enough, but I generally prefer an application package manager over a programming language package manager if possible.

If you really care, here's some bulletpoints to my preference in a nutshell:

* it's easier to get people less familiar with programming set up with
* don't have to worry about juggling different versions of node for different applications
* don't have to worry about polluting your development library space (which can result in "but it works my *my* machine issues)
* npm is more focused on library installs, and not so much on application installs, and the user experience reflects it

**Comment by mateodelnorte** [comment]
The formula link is not working

**Comment by apeschel** [comment]
@mateodelnorte How so? Does this link work better? https://raw.githubusercontent.com/apeschel/homebrew-core/new_formula/meta-git/Formula/meta-git.rb
