### ISSUE TITLE
Use of environmental variables?

### ISSUE THREAD

**Issue by TD-3294** [mateodelnorte/meta#225]
Hi,

Thanks for this tool.  One question, I would like to use environmental variables in the .meta file, so it can be used by various developers without having to change the .meta file.

I would like to have something like:

{
  "projects": {
    "project-1": "ssh://${GIT_USER}@bitbucket.org:mycompany/p1.git",
    "project-2": "ssh://${GIT_USER}@bitbucket.org:mycompany/p2.git",
    "project-3": "ssh://${GIT_USER}@bitbucket.org:mycompany/p3.git"
  }
}

Is that possible? (I tried as above and it doesn't work, variables are not resolved).

Thanks,

Juan

**Comment by mateodelnorte** [comment]
It is possible. .meta can be a json file or a .js file. When using js, simply make sure you `module.export` a valid js object.
