### ISSUE TITLE
git-meta vs meta-git vs meta

### ISSUE THREAD

**Issue by gsal** [mateodelnorte/meta#227]
## 🤓 Question

I have a need for managing (checking out certain branch or tag and deploy) several independent repos and started to google, this afternoon.  The search returned 3 very similar terms/tools and I am a bit confused.  Can somebody please briefly indicate if in fact these are 3 different tools and how they differ?   

Thanks.

**Comment by patrickleet** [comment]
git-meta is unrelated to this project

meta is the main project which loads plugins, meta-git being one of them

**Comment by patrickleet** [comment]
there's also `meta exec` in this project which lets you execute any command across repos

meta exec "git checkout -b feat/new-stuff"

**Comment by gsal** [comment]
Ah, ok; thanks.  Having heard that, will give meta a try.
