### ISSUE TITLE
project release version tracking

### ISSUE THREAD

**Issue by felix-awsi** [mateodelnorte/meta#229]
## 🚀 Feature Proposal
Provide a method for freezing the current multi-repo-state.  Higlevel versioning of a multi-repo software stack.
Given X is the meta repo and A, B and C are repositories managed by it, I want the ability to save those dependencies generically:
```
A:version 3.2 ˥
B:version 1.3 |--> X:version 1.0
C:version 5.2 ˩
```
Like submodules does i'd like to save the actual commit of my submodules.

## Motivation
We are currently developing a micro service based webapplication, where each repository provides a single service. These services use diverse technologies (go, nodejs, python). These are budled in a meta repo for easy local development and deployment. As we are in an early stage of development, changes made to one service might (sadly will) effect others. We need a method to save and recreate copies of the full stack in order to do Version Control and ease bugfixing.

## Example
To save the current state as a version:
```
meta version commit "v.1.0.0" --comment "As provided to customer C. for evaluation"
```
To checkout a version:
```
meta version checkout "v.1.0.0"
```
To verify your current version:
```
meta version status
```

## Proposal
I am aware, that you could accomplish something similar by using ```meta git tag``` and ```meta git checkout <tag>```. However these tags would then be stored in the corresponding repositories and could (obviously should not, but you know how reality usually works) be changed or moved to different commits, thus braking the stack. I propose a seperate file ".meta-version" to keep track of these versions and store commit hashes corresponding to the projects.

## Sidenote
I actually already implemented, crudely, a meta plugin for just this porpuse: [meta-version](https://github.com/felix-awsi/meta-version). However I am eager to hear whether others miss this feature as well and whether it is actually worth investing more time into polishing and making it available for others.

**Comment by IgorGee** [comment]
I think this is an essential enhancement.

I'd like to provide an alternate solution, though. Note that the following example will assume proper updates to plugins to make this work.

Consider attaching a tag/commit/branch to the list of projects via `@`.
If we want to version the meta repo at a particular commit, we could run something like:

`meta lock [--tag, --branch, --commit] [projects]`

Which would lock all or the specified projects using the desired method.

```json
  "projects": {
    "plugins/loop": "git@github.com:mateodelnorte/loop.git@{commit, branch, tag}",
  }
```

And then you can commit the meta repo as the version you'd like:

`git tag -a v1.0 -m "Initial Release"`

Key benefits to this solution:
1. Avoids an extra config file
2. Uses a familiar notation for locking dependency version (`npm`)

**Comment by felix-awsi** [comment]
I completely agree with your edit note. Having a deterministic project structure at every commit is essential to me.
Your proposal is great as well. I too would like only to use the meta file and your format would be ideal. However I felt like altering that file from a plugin would be unexpected behaviour and thus bad.
Although to be honest. Looking at it from the afor-mentioned perspective, it would be ideal not to be forced to execute any command to lock the version. It should just always be locked. Sadly I do not think this is possible, since git commands will also be executed without "meta" on a repository level. 
Would it be feasable to configure the desired version lock method (tag, commit, branch - although I think commit-hash is superiour, as it is the only truly deterministic method) in some file (or .meta) and have meta fix the versions accordingly whenever ```meta git commit``` is run?

**Comment by patrickleet** [comment]
I have never wanted/needed/desired such things.  That said, we're happy to look at pull requests.

Here's a different perspective, using microservices, as that's what you mentioned.

Every commit to master of each project should result in versioned artifact(s) being released and published to a repository.

In microservices/kubernetes, those artifacts are helm charts and docker images.

You can then have a chart which makes up your environment:

staging:
   app - v0.0.1
   serviceA - v0.0.3
   serviceB - v0.0.4

Collections of released artifacts are grouped and tested together through this additional repository that defines your environments.

When you are ready to promote staging to production, you update the versions in the production chart.

Here's an example of that (helm + docker + versioned artifacts):
https://github.com/CloudNativeEntrepreneur/environment-cldntventr-staging/blob/master/env/requirements.yaml

**Comment by patrickleet** [comment]
This also infers using trunk-based development and abandoning things like git-flow which are unnecessary added complexity
