### ISSUE TITLE
packaged version for non-node users

### ISSUE THREAD

**Issue by patrickleet** [mateodelnorte/meta#23]
maybe something like this would do the trick? https://www.npmjs.com/package/nexe

**Comment by mateodelnorte** [comment]
Looks promising. Let's do it. We'd need to create commands to install
plugins via meta, instead of npm - which probably means we'd need to bundle
npm itself within meta.

**Comment by patrickleet** [comment]
Maybe we could just bundle the core plugins as a start

**Comment by mateodelnorte** [comment]
I'd rather just bundle npm, and check PATH for npm before using the local
one. Could also have a setting in a .metarc file that tells it to use yarn,
etc, if it's present.

**Comment by aleclarson** [comment]
We could use Yarn PnP for faster startup, too. 😄
