### ISSUE TITLE
Restrict which repos are affected by `meta cmd`

### ISSUE THREAD

**Issue by manno** [mateodelnorte/meta#231]
## 🤓 Question

Is it possible to restrict the repos meta (exec, git, ...) will work on?  For example I only want to update a library in some of the [projects](https://github.com/manno/quarks-meta/blob/master/.meta).

Is there an environment variable or command line switch?

**Comment by mateodelnorte** [comment]
Yes, all `loop` options are usable from `meta`. https://github.com/mateodelnorte/loop

**Comment by manno** [comment]
Oh thanks! I looked at `exec` :)
