### ISSUE TITLE
Groups?

### ISSUE THREAD

**Issue by jfuehner** [mateodelnorte/meta#234]
Hi! Apologies if this question has been asked previously. I was curious if it is possible to perform operations on defined “groups” of repositories?

Say I have a meta repo consisting of 10 child repos. Is there a way to define a group of n child repos and then target that group by name for git operations? 

This would be similar to the “group” capability the [gita](https://github.com/nosarthur/gita) tool provides.

**Comment by patrickleet** [comment]
No, happy to review PRs though - the internals would support it.

To do this currently I just have a `Makefile` that defines the group like this:

```
NODE_APPS=app1,service1,app2,service2

node-install:
	meta npm install --include-only $(NODE_APPS)
```

Then you can run `make node-install`
