### ISSUE TITLE
Is it possible to run `meta exec` in parallel?

### ISSUE THREAD

**Issue by vviikk** [mateodelnorte/meta#236]
## 🤓 Question

Using this awesome tool to manage a ton of repos. I was wondering if we can do something like

```shell
$ meta exec "docker-compose build" --exclude web --parallel
```

Which works something like the [parallel mode in `npm-run-all`](https://github.com/mysticatea/npm-run-all/blob/HEAD/docs/run-p.md).

**Comment by vviikk** [comment]
Answering my own question. And :exploding_head: WOW.

```shell
$ meta exec "docker-compose build" --exclude web --parallel
```

JUST WORKS. Saw the [commit here](https://github.com/mateodelnorte/loop/pull/27/files).

**Comment by mateodelnorte** [comment]
Tadaaaaa. Wanna help draw us a cool cartoon for the Readme so we can get
more popular? 🤪
