### ISSUE TITLE
loop configurations not being used

### ISSUE THREAD

**Issue by Nebour** [mateodelnorte/meta#237]
## 🐛 Bug Report
Loop configuration in the .meta file or .looprc file isn't being used when executing the loop.
I know it's possible to pass the arguments like --exclude "folder", but since the file configurations are present in this repository it suggests that using the files should be possible.

## To Reproduce
Add folders to ignore in .meta or .looprc
Run a meta loop command, eg. "meta git status"
The command runs in the ignored folders

## Expected behavior
Ignored folders should be ignored when executing the loop

**Comment by patrickleet** [comment]
think you'll need a symlink for .looprc/.meta to be interchangeable, they are the same format

tbh I wasn't aware of being able to add ignored projects to either of the files, but @mateodelnorte made that part - Matt?

I usually have a Makefile like: https://github.com/mateodelnorte/meta/issues/234#issuecomment-696885985

open to reviewing PRs.

**Comment by mateodelnorte** [comment]
Correct. loop just looks for .looprc and meta inherits this. You need to
symlink to combine configuration.

**Comment by Nebour** [comment]
I tried adding the symlink but the configuration wasnt' picked up.
It seems the .looprc is only used when executing "loop" directly from the shell, and not when invoked by "meta loop".

I'm not very familiar with node development but can make an attempt to debug this, unless you have any ideas what could cause this?

**Comment by patrickleet** [comment]
use `meta exec` to loop

`meta exec "git fetch --all --tags -p && git rebase origin/master"`
