### ISSUE TITLE
Provide utility environment variables to `meta-exec`

### ISSUE THREAD

**Issue by vviikk** [mateodelnorte/meta#239]
## 🚀 Feature Proposal

Have things like current folder name (just the name, not the full path) as an environment variable you can use in commands

## Motivation

Take this for example. I have three repos (two python repos & one node)
![image](https://user-images.githubusercontent.com/1991125/112641367-9d1f6c00-8e42-11eb-97e1-eb12fcba7bc6.png)

And I run the following command:

```shell
$ meta exec "[ -f requirements.txt ] && echo dir:`pwd`" --include-only=python-project-1,python-project-2,node-project-2
```

![image](https://user-images.githubusercontent.com/1991125/112641744-f38caa80-8e42-11eb-9751-7c6ee576fe64.png)

The context or current working directory is still where I ran the command from. It would be good to have access to such things when running meta-exec. But I don't know if this should be in loop or meta-exec. An environment variable like `META_CWD`. See example below.

## Example
Say I want to create virtual environments for all my python projects with just the folder name as the venv name.

```shell
$ meta exec "[ -f requirements.txt ] && python3 -m venv --prompt $META_CWD   .venv"
```
Currently there is no easy way to do this so I just manually create my virtual environments. Hope I am making sense.

**Comment by patrickleet** [comment]
Makes sense 

try xargs though

```
meta exec "pwd | xargs basename | xargs echo"
```

for venv

```
meta exec "pwd | xargs basename | xargs python3 -m venv .venv --prompt"
```

For example:

```
meta exec "pwd | xargs basename | xargs python3 -m venv .venv --prompt" --include-only=plugins/meta-loop
```

![image](https://user-images.githubusercontent.com/474827/112683989-69dbdd80-8e40-11eb-8a12-f11651309764.png)

**Comment by vviikk** [comment]
What manner of sorcery is this? And why does this work lol?!

**Comment by patrickleet** [comment]
You were having trouble with environment variables - the command `pwd` always worked directly. 

Seems that when you use in as env var it gets evaluated before being executed in each repo.

so `pwd` returns the directory name.. then it is piped to `xargs` which, as a simple explanation, basically puts it as an argument to the command..

basename gets the directory name, and the result of that is piped to the next xargs command.

**Comment by patrickleet** [comment]
I didn't try this before, but escaping the `'s also works:

```
➜  meta exec "echo `pwd`" --include-only=plugins/meta-loop

plugins/meta-loop:
/Users/patrickleet/dev/mateodelnorte/meta
plugins/meta-loop ✓
```

```
➜  meta git:(patrickleet-patch-1) meta exec "echo \`pwd\`" --include-only=plugins/meta-loop

plugins/meta-loop:
/Users/patrickleet/dev/mateodelnorte/meta/plugins/meta-loop
plugins/meta-loop ✓
```

**Comment by patrickleet** [comment]
I added a note to the README: https://github.com/mateodelnorte/meta#how-to-escape-expressions

**Comment by vviikk** [comment]
Legend, thanks.
