### ISSUE TITLE
meta commands apply not only to .meta projects, but to the current directory also.

### ISSUE THREAD

**Issue by agwaltz** [mateodelnorte/meta#25]
I expected "meta" to _only_ perform operations in each sub-directory in the .meta file.  However, it also tries to perform operations in the current directory.  

Is there a way to disable this, or is it a bug?

**Comment by mateodelnorte** [comment]
This is by design. If you don't want to include your meta repo, just add `--exclude [meta foldername]` and you'll exclude it. 

It makes sense for operations like `meta git status` or `meta git pull` that you'd also pull any changes in the meta repo, itself.

**Comment by mateodelnorte** [comment]
the full example command, when working in the meta folder for instance, would be `meta git status --exclude meta`

**Comment by Sebastian-Fitzner** [comment]
Can you add that to the documentation? Searched for that more than a couple of minutes ;)

**Comment by mateodelnorte** [comment]
Sure thing. Also, just a quick note on the title of the issue – Meta includes both the parent _repo_ and child repos, not the current directory.

**Comment by mateodelnorte** [comment]
> meta is powered by plugins that wrap common commands, letting you execute them against some or all of the repos in your solution at once. meta is built on loop, and as such inherits loops ability to easily target a particular set of directories for executing a common command.

looks like it was already in there, just without an example or a link.

**Comment by mateodelnorte** [comment]
updated with slightly clearer language and an example.

**Comment by Sebastian-Fitzner** [comment]
> looks like it was already in there, just without an example or a link.

To be more specific, I have read that but had no clue how the command for it is. 

> meta git status --exclude meta

With that simple line almost everything is clear (meta as directory and package name would not be the best example but it works)

**Comment by jeremyalan** [comment]
Here's another alternative, that works well for me, as it puts a command in my Bash history that I can use regardless of which meta-repo I'm working in.
```
meta exec --exclude "${PWD##*/}" "git s"
```
In this sample, `${PWD##*/}` prints the current directory, so it works well if you have multiple meta-repos that you switch between, and just want a single command that you can refer to regardless of which repo you're running from.
