### ISSUE TITLE
Windows - Powershell or cmd, meta git commit -m " " and a space in user name

### ISSUE THREAD

**Issue by nn-afly** [mateodelnorte/meta#258]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

running a meta git commit -m " " in powershell or cmd throws an error if the user has a space in their user profile folder and the commit message contains a space

## To Reproduce

Have a profile with a space in it e.g. "c:\Users\Firstname Lastname\"
meta git commit -m "message with spaces" 

For each repo an error will occur

'C:\Users\Firstname' is not recognized as an internal or external command,
operable program or batch file.

It doesn't matter whether the meta repo is in the user folder or not. The error will occur

**Comment by mateodelnorte** [comment]
Would gladly accept a PR on this one.

**Comment by patrickleet** [comment]
yea gotta be honest, haven't used windows for development in probably 8 or 9 years now
