### ISSUE TITLE
"commander": "mateodelnorte/commander.js" issue

### ISSUE THREAD

**Issue by reggi** [mateodelnorte/meta#26]
Hey Matt!

Im having issues adopting this behind a proxy because of the github connection for `commander` module.

https://github.com/mateodelnorte/meta/blob/master/package.json#L36

Is there any way we can make this a NPM dependency?

**Comment by reggi** [comment]
@mateodelnorte is it possible for you to publish this as a scoped package? 

https://github.com/mateodelnorte/commander.js

**Comment by reggi** [comment]
I believe I found a work around so not super essential.

**Comment by mateodelnorte** [comment]
I'd prefer if we just got this PR merged:
https://github.com/tj/commander.js/pull/604

It was created in January.

**Comment by mateodelnorte** [comment]
You can set ssl-strict to false in npm config if you want to get around it.
