### ISSUE TITLE
Command Injection in meta-git

### ISSUE THREAD

**Issue by nguyenth** [mateodelnorte/meta#262]
## 🤓 Question

Do we have a plan for resolve the advisory:
https://github.com/advisories/GHSA-qcff-ffx3-m25c

**Comment by patrickleet** [comment]
Hm, running commands you give it is kinda the point. It is a tool for development. Happy to accept a PR to meta-git that sanitizes the input git url.

https://github.com/mateodelnorte/meta-git/blob/master/bin/meta-git-clone#L15-L21

**Comment by patrickleet** [comment]
oh wait, did I try to do this two years ago? did that not work?

I don't remember the context of this:
https://github.com/mateodelnorte/meta-git/commit/affdd44225d79398b3f8d5eb6183089126bba8c6

EDIT: Toufik Airane authored, I only committed... maybe a squash?

**Comment by patrickleet** [comment]
https://github.com/mateodelnorte/meta-git/pull/56

**Comment by patrickleet** [comment]
Yea this is fixed - you can try the example from the report and see it just errors

```
meta-git clone 'sss||touch HACKED'meta git cloning into 'ssstouch HACKED' at ssstouch HACKED

ssstouch HACKED:
fatal: Too many arguments.
```
and no `HACKED` file created

```
> ls -la | grep HACKED
```

**Comment by patrickleet** [comment]
the hackerone report it references also says "Resolved(Closed)"

![image](https://user-images.githubusercontent.com/474827/126047754-51e759a4-bd3a-40f7-a964-e00b0ec95227.png)

**Comment by patrickleet** [comment]
looks like this can be updated in settings? @mateodelnorte 

https://docs.github.com/en/code-security/security-advisories/about-github-security-advisories
