### ISSUE TITLE
Unable to install meta

### ISSUE THREAD

**Issue by Sivaganesh-Akula** [mateodelnorte/meta#270]
## 🤓 Question

C:\Users\user-directory>npm i -g meta
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/mateodelnorte/commander.js.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\akula.sivaganesh\AppData\Roaming\npm-cache\_logs\2021-06-09T05_24_27_713Z-debug.log

**Comment by patrickleet** [comment]
do you have an ssh key set up?

**Comment by Sivaganesh-Akula** [comment]
Yes

Anything specific required for this?

**Comment by mateodelnorte** [comment]
This is an issue with your GitHub setup, not with meta. Ensure you can clone GitHub repos and ssh is configured correctly.
