### ISSUE TITLE
Question: Can I tell `meta exec` to run commands using Powershell insetad of CMD?

### ISSUE THREAD

**Issue by eddex** [mateodelnorte/meta#276]
## 🤓 Question

I'm using meta on Windows 10 in PowerShell 7.1.3. When I run `meta exec "<some command>"`, meta seems to use `cmd` instead of Powershell to run the command.

Example: 
- `meta exec "dir"` works fine
- `meta exec "Get-ChildItem"` returns an error "'Get-ChildItem' is not recognized as an internal or external command"

Of course I can run Powershell commands like this: `meta exec "pwsh -c Get-ChildItem"`. But I'd like to be able to just pass in a Powershell command to `meta exec`.

Is there a way to change the default shell `meta exec` uses to run the commands?

**Comment by patrickleet** [comment]
Not currently, but looks very doable - PRs welcome - would go in here as an option passed to the call:
 https://github.com/mateodelnorte/meta-exec/blob/master/index.js
 
 https://stackoverflow.com/a/61219838/237676
