### ISSUE TITLE
meta yarn install

### ISSUE THREAD

**Issue by jjenzz** [mateodelnorte/meta#28]
I may be misunderstanding things but when I ran `meta project add <folder> <repo>` it created an empty folder with the folder name I specified. I assumed it would contain the files/folders from the repo but it didn't so I tried `meta yarn install` and nothing improved.

I then tried `meta yarn clean` which removed the meta project `node_modules` and re-tried `meta yarn install` but it did nothing, in fact it didn't even install the meta project `node_modules`.

Where am I going wrong here? 

I have:

```
node 8.9.4
yarn 1.3.2
meta 1.0.48
meta-yarn ^0.0.4
```

**Comment by jjenzz** [comment]
Oh, I'm guessing my other repo has to be a meta project too? :woman_facepalming:

**Comment by mateodelnorte** [comment]
Nope. You just need to cd into that repo and git pull origin master your
files down, assuming, they already exist. meta-git doesn't know if you've
already created your remote or not, so it doesn't attempt to pull them down
for you.
