### ISSUE TITLE
How to make meta to run only on child repositories and not on the root meta repo itself?

### ISSUE THREAD

**Issue by khelkun** [mateodelnorte/meta#285]
## 🤓 Question
`meta ` runs in all child repositories but also first run on the root repository e.g the meta repository itself.

I can imagine why this is the default aim of `meta` but I wish I could avoid this and just make `meta` to run in all the child repositories declared in the `.meta` but not on the meta repository itself.
Is there a way to do that please?

**Comment by patrickleet** [comment]
assuming your meta repo is named "meta"

```
meta exec "pwd" --exclude "meta"
```

**Comment by patrickleet** [comment]
or from the root of the meta repo, find the name of it programatically 
```
meta exec "pwd" --exclude $(basename `pwd`)
```

**Comment by khelkun** [comment]
thanks @patrickleet, this works all my meta commands.

I don't see this `--exclude` option in the README, and actually I don't see where it's implemented.

Is there others meta command options not documented in the README? Where those options are implemented?

For example I wonder if `meta` has an option like `--projects-file=.meta-myprojects`.

**Comment by mateodelnorte** [comment]
meta inherits from https://github.com/mateodelnorte/loop. As such, any
options you can pass to loop can also be passed to meta.
