### ISSUE TITLE
`pnpm i -g meta; meta` fails to locate any commands

### ISSUE THREAD

**Issue by vjpr** [mateodelnorte/meta#30]
Not working with `pnpm` package manager. https://github.com/pnpm/pnpm

There must be something about the way it looks for plugins that is non-standard. Maybe it expects them all to be top-level deps, which is not really reliable.

**Comment by vjpr** [comment]
https://github.com/mateodelnorte/meta/blob/master/lib/listDirectories.js#L40

This line is preventing it from working.

In `pnpm`, every package in `node_modules` is a symlink.

**Comment by mateodelnorte** [comment]
Pull requests welcome. ;) Otherwise, will be a while before I can get to it.

**Comment by aleclarson** [comment]
I'd recommend not closing an issue that isn't fixed yet. :)

I will tackle this puppy.

**Comment by patrickleet** [comment]
@aleclarson sounds good - reopened for you

**Comment by aleclarson** [comment]
@patrickleet I'll be writing some tests with Jest for my PR. Can you setup Travis CI or similar?

**Comment by aleclarson** [comment]
Or give me permission to set that up. ;)

**Comment by patrickleet** [comment]
@mateodelnorte will have to - I have push permissions to repo but that doesn't allow me to set up travis.

We were planning on adding it with semantic release soon.

@mateodelnorte can you activate this and any `meta-*` repos on travis when you get a chance?

**Comment by aleclarson** [comment]
I would recommend setting up codecov.io too. Works nicely.

**Comment by aleclarson** [comment]
Also, did you want to setup Jest as well? Otherwise, I can.

**Comment by patrickleet** [comment]
these are my usuals - https://hackernoon.com/these-6-essential-tools-will-maintain-your-npm-modules-for-you-4cbbee88e0cb

yea jest is great go for it - I added codecov.

also turns out I can activate travis by just pushing a new .travis.yml file.

Also travis-ci.org is legacy now?

**Comment by aleclarson** [comment]
> also turns out I can activate travis by just pushing a new .travis.yml file.

I assume that's because of a Github app?

> Also travis-ci.org is legacy now?

I guess so. I'm still using it, because Coveralls doesn't seem to work with Travis' Github app.

**Comment by patrickleet** [comment]
snyk is also worth adding to everything

**Comment by aleclarson** [comment]
Yes very true. That came into my radar recently, too. I'm also a fan of lint-staged and husky together.

**Comment by aleclarson** [comment]
What's the point of `travis-deploy-once`?

**Comment by aleclarson** [comment]
Btw, do you prefer nested `__tests__` directories or root-level `spec/tests` directory?

**Comment by aleclarson** [comment]
Just found [LGTM](https://lgtm.com) which watches for security vulnerabilities (like Snyk) and also does code analysis. Might be worth checking out.

**Comment by aleclarson** [comment]
This is still an issue.

Meta is trying to use:
```
~/.nvm/versions/node/v11.10.1/meta-project/2.2.0/node_modules/meta-project/bin/meta-project
```
but this is the path we really want:
```
~/.nvm/versions/node/v11.10.1/pnpm-global/2/node_modules/.registry.npmjs.org/meta/2.2.2/node_modules/meta-project/bin/meta-project
```

**Comment by aleclarson** [comment]
This is fixed now! 🥳

**Comment by mateodelnorte** [comment]
Tadaaaaaaaaa!
