### ISSUE TITLE
Unable to reuse one react component in another react app repository

### ISSUE THREAD

**Issue by vineet0609** [mateodelnorte/meta#307]
## 🤓 Question

This is my project structure.

MetaRepo:-
     ReactChild-1:-
        src -> component -> index.js
        node_modules
        package.json
     ReactChild-2:-
        src -> component -> index.js
        node_modules
        package.json
node_modules
package.json

    

I want to use meta repo for multiple react projects. 

Right now I have two react-based projects ReactChild-1 & ReactChild-2.

I want to reuse the code of one component from ReactChild-2 into ReactChild-1.

I have run the command :- meta npm link --all

it's linking all the child repo into node_modules of meta repo (at root level)

but I'm unable to understand how I will import components from ReactChild-2 into ReactChild-1.

and I am getting the following error.

Module parse failed: Unexpected token (8:8)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| const DisplayMessage = () => {
|     return (
>         <h4>This is testing message coming from lens app</h4>
|     )
| }

Please help me.

Thanks in advance.

**Comment by vineet0609** [comment]
@mateodelnorte , could you please help me on this?

**Comment by mateodelnorte** [comment]
Hi. This is a webpack issue, not a meta issue. I’d suggest researching how
to use npm link and webpack together.
