### ISSUE TITLE
Error running meta init (Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by westridge97330** [mateodelnorte/meta#31]
Getting the following error when running meta init:

[SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode]

Is this related to the node vs. nodejs version issues noted here:

[https://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu/38325376#38325376](url)

**Comment by mateodelnorte** [comment]
Is that the full stack trace of the error you're seeing?

**Comment by mateodelnorte** [comment]
What version of node are you using? `node -v`

**Comment by westridge97330** [comment]
Yep, that is all that is emitted.

v4.2.6

**Comment by westridge97330** [comment]
Problem solved. Thanks for the pointer.

Linux novice here so I did not realize that apt-get would not install the latest.  I installed from source it it appears to be working.

**Comment by mateodelnorte** [comment]
No problem. Most people use `n` or `nvm` for version management. Cheers.
