### ISSUE TITLE
feature request - ability to specify --recurse option

### ISSUE THREAD

**Issue by mateodelnorte** [mateodelnorte/meta#32]
feature request - ability to specify --recurse option, to recognize child meta repos and repeat command for them and their childre

**Comment by marcguilera** [comment]
Is this something being worked on at all? Would be nice to have a parent meta which contains other metas.

**Comment by mateodelnorte** [comment]
You can already have metas within metas, no problem. You just can't exec a
command recursively through them.

**Comment by marcguilera** [comment]
Okay, so the recurring aspect of it doesn't work. 

Say you have a meta.all pointing to a meta.tools and meta.frontend. When cloning `meta.all` doing `meta git pull git_path_to_meta_all` the nested repositories won't be pulled as well, right?

**Comment by mateodelnorte** [comment]
Correct. And in many cases, that's what you want.

**Comment by marcguilera** [comment]
Thanks, sounds reasonable. It would be cool to have that option though 👍 .
