### ISSUE TITLE
is there a feature where you can meta git checkout <sha#>

### ISSUE THREAD

**Issue by elimau** [mateodelnorte/meta#36]
is there a meta git checkout feature?
e.g. meta git checkout <sha#>

Doing that will checkout that <sha#> in one of the repos. It will change all the other repos to be checkedout to the latest commit at that time of that <sha#>.

The reason for this feature is that some people prefer mono repos over multi repos because they get a snapshot of the whole stack when they checkout a <sha#>. So this will cover that scenario.

Thanks!

**Comment by mateodelnorte** [comment]
You can certainly do `meta git checkout <sha#>`. But it won't check out the latest commit in other repos. It will just fail the command and leave them where they are. 

What's your use case? If you're trying to jump to points in time, like releases, across your library or system you can just do `meta git tag v0.0.1` to tag all projects (don't forget to `meta git push origin v0.0.1`), after which you can do a `meta git checkout v0.0.1` at any time.
