### ISSUE TITLE
Running any subcommand throws SyntaxError on Windows

### ISSUE THREAD

**Issue by andreeib** [mateodelnorte/meta#37]
Running any subcommand throws a SyntaxError on Windows:
```
$ meta git clone git@github.com:mateodelnorte/meta.git
C:\Users\Andreeib\AppData\Roaming\npm\node_modules\meta\node_modules\.bin\meta-git.cmd:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

```
$ node -v
v8.11.1

$ npm -v
5.8.0
```

If I replace this line:
https://github.com/mateodelnorte/commander.js/blob/245bc4c84ba72d447ab30ec3e2a4456e34052b59/index.js#L576 
with:
`proc = spawn(bin, args, { stdio: 'inherit', customFds: [0, 1, 2] });` 
it works.

In windows the npm bin is a batch file and not JavaScript.
```
meta-git-clone.cmd
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\meta-git\bin\meta-git-clone" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\meta-git\bin\meta-git-clone" %*
)
```

**Comment by kdblitz** [comment]
I've also experienced a similar issue as OP, when I cloned the meta repo:
And I'm unable to use the meta clone command, as well as the other commands.

```bash
$ node -v
v8.11.1

$ npm -v
5.6.0
```

**Comment by mateodelnorte** [comment]
I'll get this fixed today, if I can. Thanks for reporting.

**Comment by jsuhard** [comment]
Hi,

the proposed fix is not sufficient : commands are well executed but not show up in the prompt

I make a PR to fix this issue : https://github.com/mateodelnorte/commander.js/pull/1

**Comment by jsuhard** [comment]
Hi @mateodelnorte,

as https://github.com/tj/commander.js/pull/604 seems to hang, do you mind to release now a new NPM package with this fix ?

Thanks,

**Comment by mateodelnorte** [comment]
will do.

**Comment by jsuhard** [comment]
Hi @mateodelnorte ,

as commander dependency is from your github (who already contains the fix), new install from scratch is working fine on Windows :-)

**Comment by kdblitz** [comment]
Hi @mateodelnorte,

I confirm what @jsuhard said: performing a fresh install of meta globally already fixes the issue on Windows! :+1:

**Comment by mateodelnorte** [comment]
Great. Thanks 😁
