### ISSUE TITLE
Use folder name in "meta exec"

### ISSUE THREAD

**Issue by jeremyalan** [mateodelnorte/meta#38]
Is there a way to get the current folder name, when running a command via `meta exec`?

Here's a concrete example of what I'm hoping to accomplish (although, I could foresee a handful of other scenarios where this might be useful):

We have a meta-repo, containing a `.meta` file with a bunch of other projects that all depend on each other.  These sub-repos contain .NET Standard projects, and I would like run a command to compile and publish (to a local feed) each project one-by-one.

For example...
```
rmdir %USERPROFILE%/.nuget/packages/<name-of-project> /s /q
dotnet pack src/<name-of-project>/<name-of-project>.csproj --configuration Release --output package
nuget push -Source %USERPROFILE%/.nuget/packages/ src/<name-of-project>/package/<name-of-project>.<version>.nupkg
```

Due to the folder structure we have in place, the command that I'm running changes depending on which project I'm building, if that makes sense.

**Comment by mateodelnorte** [comment]
Totally agree here. Would be great to have access to some magic parameter names for commands. The change would likely be made in [loop](https://github.com/mateodelnorte/loop). 

Interested in making a pull request?

**Comment by jeremyalan** [comment]
Yep, I haven't looked closely at either codebase, but I'd be happy to take a stab at it when I can carve off a few hours to dig in deeper.

**Comment by mateodelnorte** [comment]
Was just thinking about this and wondering, is something like the following good enough? 

```
loop 'echo `pwd`'

bin:
/Users/matt/development/loop/bin
bin ✓

lib:
/Users/matt/development/loop/lib
lib ✓

support:
/Users/matt/development/loop/support
support ✓

test:
/Users/matt/development/loop/test`
```
You can also get just the top level folder name: 
```
loop 'echo `basename \`pwd\``'

bin:
bin
bin ✓

lib:
lib
lib ✓

support:
support
support ✓

test:
test
test ✓
```
No code is always better than code to maintain, and if this works, I just add the example to the readme.

**Comment by jeremyalan** [comment]
That's not too far from what I ended up doing, except I needed the current folder name, not the full path, but I found a bash equivalent for that also.

I'll try to send a copy of the final script we've been using, that might help.

**Comment by jeremyalan** [comment]
Here's the script, that I put in a `scripts/` folder in my meta repo:
```
#!/bin/bash

WinUserDirectory=`cmd.exe /c "<nul set /p=%UserProfile%" 2>/dev/null`
UserDirectory=`wslpath ${WinUserDirectory}`
NugetPackageFeed=${UserDirectory}/.nuget/packages
ProjectName=${PWD##*/}

rm -rf ${NugetPackageFeed}/${ProjectName}
find . | grep bin$ | xargs rm -rf
find . | grep obj$ | xargs rm -rf

powershell.exe -Command "dotnet pack src/${ProjectName}/${ProjectName}.csproj --configuration Debug --output package"

dotnet nuget push src/${ProjectName}/package/*.nupkg --source ${UserDirectory}/.nuget/packages
```

Then, when I want to locally publish all the NuGet packages in my meta repo, then I just run:
```
$ meta exec --exclude "${PWD##*/}" ../scripts/publish.sh
```

There's a lot of boilerplate in that script, but I figured no reason to sanitize it too much, I wanted you to see the "real world" solution. 😄 

In the end, it's not so bad.  I posted this question before I came up with a final solution, and I agree that less code = better code, so if you want to close this out, I'm good with that!  Sorry I haven't had a chance to follow up on this, trying to wrap up a few other projects at the moment.

**Comment by jeremyalan** [comment]
Honestly, I should probably just wrap this up into a `meta` plugin, to avoid copying this script into all my meta repos, then I could just run:
```
$ meta nuget publish
```

I'll add it to my pile. 😉

**Comment by mateodelnorte** [comment]
Closing since this is getting satisfied by a plugin. 

@jeremyalan any chance you'd like to publish a `meta-nuget` and have it linked to from the main `meta` repo?
