### ISSUE TITLE
No errors on invalid commands

### ISSUE THREAD

**Issue by quezak** [mateodelnorte/meta#39]
Using an unsupported command yields no output and a successful exit code.
I think it should write an error message, and certainly not return 0.

Some example cases (the 0 in my prompt is the exit code of the last command):

```
# calling meta with a random word
   0[quezak@...]...$ meta asdf
# calling meta git with a random word
   0[quezak@...]...$ meta git asdf
# calling meta git with an alias to git status (in my ~/.gitconfig) -- shouldn't this produce same output as meta git status?
   0[quezak@...]...$ meta git s
   0[quezak@...]...$
```

**Comment by mateodelnorte** [comment]
This is an issue with Commander.js, which meta uses. The best place for the
issue is there.
