### ISSUE TITLE
meta init command

### ISSUE THREAD

**Issue by patrickleet** [mateodelnorte/meta#4]
It'd be great if there were a `meta init` command that could be used to bootstrap your meta setup.

At a minimum it should create a .meta file, with the basic JSON structure.

**Comment by mateodelnorte** [comment]
Created  https://github.com/mateodelnorte/meta-init and added to meta in c68c803b3a46ea8f9b6379c0e925703b77cafddd.

**Comment by mateodelnorte** [comment]
Has basic .meta file creation now, and placeholders for logic to locate git repositories in cwd child directories and add to projects property.
