### ISSUE TITLE
origin refspec doesn't work when pushing new branch to remote

### ISSUE THREAD

**Issue by Damienmarble** [mateodelnorte/meta#42]
If I create new branches via `meta git checkout -b new_branch`, the new branches cannot be pushed as I would expect via `meta git push -u origin new_branch`, with each execution in the child directories failing with `error: src refspec origin does not match any.`

If I manually cd into the directories and execute the command or execute it via `loop "git push -u origin new_branch"` it works as expected. After the new branches are present in the remote repository, `meta git push` works as expected.

**Comment by patrickmarabeas** [comment]
The following does the trick: `meta git push origin HEAD:new_branch`
