### ISSUE TITLE
meta attach

### ISSUE THREAD

**Issue by patrickleet** [mateodelnorte/meta#5]
Setting up meta is currently a manual process.

A `meta attach` command would automate adding projects to the .meta file, as well as .gitignore

**Comment by mateodelnorte** [comment]
This will go into https://github.com/mateodelnorte/meta-project via a `meta project add` command.

**Comment by mateodelnorte** [comment]
`meta add x y` will now do this for you. https://github.com/mateodelnorte/meta-project. it's included as a child command in meta by default.
