### ISSUE TITLE
Convert submodules to meta?

### ISSUE THREAD

**Issue by kevin-olbrich** [mateodelnorte/meta#51]
Hi!

Often I get detached HEADs when working with submodules in a meta project (which is immense pain).

How can I move from submodules to meta? I want to work in a single project root and split commits into their own module-repo's.

Thank you.

**Comment by mateodelnorte** [comment]
To add to @patrickleet's suggestion for just importing them as new meta child projects, you can always have meta repos within meta repos. So, if you have, say, a meta repo now with a bunch of child repos that each use submodules – just turn those child projects into meta repos and add the used-to-be-submodules as child repos of that meta repo.
