### ISSUE TITLE
Better ergonomics for scripts

### ISSUE THREAD

**Issue by christianbundy** [mateodelnorte/meta#52]
Hello!

I've been using your project to manage about 150 repos and I've been loving it. I've had a few pain points, but one is that *many* of my `meta exec` statements only apply to a few repositories. For example, I'll do something like this:

**`script.sh`**

```sh
if ! [ -a .meta ]; then
  BRANCH=$(git remote show origin | grep "HEAD branch" | sed "s/.*: //")
  git fetch origin
  git checkout $BRANCH
  git reset --hard origin/$BRANCH
  git clean -fdx
  if [ -a package.json ] && ! [ -a .gitignore ]; then
    echo 'node_modules' > .gitignore
    git add .gitignore
    git commit -S -m 'Add .gitignore to ignore node_modules'
    git push origin $BRANCH
  fi
fi
```

```sh
meta exec "$(< script.sh)"
```

Here are my pain points:

- I'll often want to exclude the meta repo, and this seems better suited to a CLI flag than `if ! [ -a .meta ]`
- I *only* want to run commands on repos with `package.json`, but I get output from all repos -- it would be great if repos without any stdout just didn't show up at all
- I personally don't mind the shell command above, but `meta exec -f script.sh` might be more ergonomic

Thanks for your work on this project, I'm loving it!

**Comment by mateodelnorte** [comment]
Hi there @christianbundy. First off, thanks for using `meta`! Glad you're having such success with it. 

I typically use a `Makefile` and the capabilities that `meta` inherits from [loop](https://github.com/mateodelnorte/loop#loop) to get these types of things done. `loop` allows you to do things like `loop "pwd" --include-only this-dir, that-dir` or `loop "pwd" --exclude .` (<-- that will exclude the meta dir). 

Note, if you want to use these in ci,  there are also flags for controlling exit codes for the commands. You can, for instance, do `--exit-on-aggregate-error` and ensure all commands will run and return a 1 if any single command exited with code 1. You can also directly `npm i --save-dev meta-npm` and do things like `meta-npm run test --exclude project-one, project-two --exit-on-aggregate-error` to run npm commands against only your node projects, in ci.

**Comment by mateodelnorte** [comment]
And, just to be clear, since `meta` inherits these capabilities from `loop`, you can do: 

`meta exec "my command" --include-only dir-one, dir-two`

All loop options apply to anything you can do with `meta`.

**Comment by christianbundy** [comment]
Cool! Looks like I should likely spend some more time looking at the loop docs.

I suppose *really* the problem that I'm trying to solve here is that I have heterogeneous repos, and the only thing keeping them "together" in the same meta repo is that they belong to the same GitHub org. Maybe some sort of labeling scheme may be more appropriate? For example, when I check `[ -a package.json ]` what I'm really looking to determine is whether it's a JavaScript project, but maybe something like this would be better:

```shell
meta exec "if [ -a package.json ]; then meta label js; fi"
meta exec "pnpm install"  --include-only-label js
```

I'm sure others are using meta and loop for other things, but it seems like I'm using it to basically run migrations on repos, ensuring that they all have `.gitignore`, `package-lock.json` or `.npmrc`, some sort of README, etc.

Btw, if there's a better place for these hand-wavey feature "requests" please let me know. I'm only using GitHub issues because it's easy and I'm lazy, but please feel free to close this issue if you'd rather only accumulate bug reports. :+1:

**Comment by mateodelnorte** [comment]
I've built some of this into the plugins, themselves. `meta-loop` allows you to pass an options object with a `test` property which accepts a function that returns a boolean. If that boolean is true, `meta-exec` will run on the current dir. Else, it will skip. 

https://github.com/mateodelnorte/meta-npm/blob/master/bin/meta-npm-install#L13

@patrickleet has talked about having keys or groups of projects, which could be referred to in commands. I think that's not a bad idea, but I'd also like to watch out for cluttering up commands as much of the power of these tools is just how simple they are.

**Comment by patrickleet** [comment]
I have meta repos of meta repos, which may or may not make sense for your project, but keep in mind you can slice and dice things different ways and even for different use cases. The same project can exist in many meta repos.

You could make a meta repo called 'node-projects' and then run those maintenance type commands from there.

Lately, I've been using a meta repo per bounded context, which maps to a deploy to a single helm chart that describes that context and the versions of each of their services.

**Comment by mateodelnorte** [comment]
Do the above solutions fit your need @christianbundy? Will close if so.

**Comment by christianbundy** [comment]
Yep, it sounds like I should probably drop down into custom JS for this sort of thing. Thanks for the help!
