### ISSUE TITLE
[Question] Tagging Repositories

### ISSUE THREAD

**Issue by johannesschobel** [mateodelnorte/meta#55]
Dear @mateodelnorte ,

i am currently evaluating this package for future use in my projects as i want to provide an easy to maintain approach for splitting up my packages into different modules and then building it all together.

I have a question, which i as not able to answer so far:
Is it possible to tag all sub-packages from the main repository? e.g., if i release a new version of my main application, can i `tag` all sub-packages at the same time? 

Consider the following example:
I will release a `2.0.0` version of my main application and, therefore, adapt all my other packages. However, i would like to automatically tag them as well with `2.0.0` to have a consistent state across my overall application.

Is this possible? If yes, how?
All the best

**Comment by mateodelnorte** [comment]
Yup. Quite easy. `meta git tag [tagname]`

https://github.com/mateodelnorte/meta-git/blob/master/bin/meta-git-tag

**Comment by johannesschobel** [comment]
hahahaha.. ok, sorry for bothering you with this issue..
Awesome support! Thank you very much!
