### ISSUE TITLE
meta git pull... 

### ISSUE THREAD

**Issue by pociej** [mateodelnorte/meta#56]
... fails, even on public project. What i did i initialized meta then i added some repos using `meta project add [name][repo]` and after `meta git pull` i see " 

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[name]: command 'git pull ' exited with error: Error: Command failed: git pull
``` 

And its not repo specific issue, i tried my own repos, open source plugins its always like that.

**Comment by mateodelnorte** [comment]
You have something wrong with your GitHub ssh keys. You may have used sudo
to install meta globally, which would mean it's using your root keys.

**Comment by pociej** [comment]
No its not installed by sudo. I will check meta implementation and debug.

**Comment by pociej** [comment]
Close the issue please. I don't know where is issue, but for sure it is local problem as on two other machines with same OS it worked.
