### ISSUE TITLE
advice around https vs ssh for repo additions

### ISSUE THREAD

**Issue by wes1278** [mateodelnorte/meta#59]
Right now, I've got this working wonderfully if I add projects using https. But, I use bitbucket and the url is something of the form: https://username@bitbucket.org/organization/repo.git

I'd like to force my development staff to use this if possible, but they'd all have to change the username in the .meta;

I did get it to work with ssh when I added the project with the format `git@bitbucket.org:organization/repo.git` but it was challenging to say the least and I had ssh whining at me for quite a bit.

Perhaps I'm just ignorant to an easier way. Perhaps I should just write a script that's inside my metarepo; But I'm very fond of just using meta git clone metarepourl to clone everything. If I had to script the updation of the .meta file to hot-swap the end-users username, it wouldn't work etc..

Perhaps you can point me to some best practice around using this in teams? 

For what it's worth, I'd love to figure this out and help you document the add project module a bit more; It was hard to tell if I just entered the repo wrong, or it was an ssh problem etc...

**Comment by mateodelnorte** [comment]
I always try to use ssh, as https will often force you to enter a password when performing operations. So, you'll have to constantly re-enter your password. ssh will use your key pair, and avoid this. 

That said, I had this same issue with a client who was using an internally hosted bitbucket. Your .meta file can actually be a js file, if you like. So, you can have 
```
const username = process.env.USERNAME
module.exports = {
  "project": "https://${username}@butbucket.org/org/repo.git"
}
```

**Comment by dgradl-fl** [comment]
These guys have a similar tool but I like the simplicity of meta better: https://github.com/prezi/pride . However they do have a global config file in the user home directory where you can set up your base repo url like git@bitbucket.org/whatever or https://bitbucket.org and their metadata file just has the suffix.   Might be an idea for dealing with this.   Surely we could use a bit of javascript code to handle that - but might be a nice core feature.

**Comment by mateodelnorte** [comment]
Looks like their tool is specific to projects that use gradle. I don't know why people prefer to bundle concerns with tools like this. pride and lerna would both probably better if they worked for any platform.

**Comment by dgradl-fl** [comment]
Yeah, I agree.. I just thought the idea was useful, how they store the repository path in a user config file whether it be ssh or https end point and that way different team members can choose their preference.

**Comment by mateodelnorte** [comment]
Sounds like more code to maintain, and an easy way to make there need to be a magic file your devs have to exchange to make things work. With meta and a single Makefile, your devs can completely onboard with a single command. Here's one I use for a current client: `npm i -g meta && meta git clone git@github.com:my-client/my-client-meta.git && cd my-client-meta && make onboard`. That will install all common tools the client's engineers use, clone all repos, npm install all repos, clone a QA database, and run everything in docker containers. You run one command and come back to a fully running system. When you externalize a single file required for your repo to work, you now have one more external dependency for all that to work.

**Comment by dgradl-fl** [comment]
All you do there is  `pride config repo.base.url git@bitbucket.org:whatever` and it just drops a hidden config file in your $HOME.    And it uses that to prefix your repos, which lets devs set that whether they want to use ssh or https and can easily be chained into your single command.     I too would prefer everyone just use ssh.  I was just offering this idea I saw over there as a suggestion so you can leave it open for developers to choose which way to go and address the original question on the ticket.
