### ISSUE TITLE
meta init

### ISSUE THREAD

**Issue by reggi** [mateodelnorte/meta#6]
I ran `touch .meta`, then needed `package`.

```
/Users/thomas/.nvm/versions/node/v7.2.1/lib/node_modules/meta/node_modules/meta-git/bin/meta-git-clone:51
  const projects = meta.projects;
                       ^

TypeError: Cannot read property 'projects' of null
    at exec (/Users/thomas/.nvm/versions/node/v7.2.1/lib/node_modules/meta/node_modules/meta-git/bin/meta-git-clone:51:24)
    at module.exports (/Users/thomas/.nvm/versions/node/v7.2.1/lib/node_modules/meta/node_modules/meta-exec/index.js:54:18)
    at Object.<anonymous> (/Users/thomas/.nvm/versions/node/v7.2.1/lib/node_modules/meta/node_modules/meta-git/bin/meta-git-clone:21:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

**Comment by reggi** [comment]
hmm still complains even with 

```
{
  "projects": {}
}
```

**Comment by reggi** [comment]
I'm already stuck :(

I have to repos I want to bring in and no clue how to bootstrap `.meta` even if I manually enter it I don't know how to pull them down 🤔

**Comment by mateodelnorte** [comment]
you need to do a `git init` in your meta repo. I've got a new plugin https://github.com/mateodelnorte/meta-init that is going to do all this for you in a single command. will be done in a couple days or less.

**Comment by mateodelnorte** [comment]
to get started: 

1. mkdir somedirectory
2. cd somedirectory
3. git init
4. npm init
5. npm i meta-npm
6. modify your .meta file to look like the following, if you're making a system of services and sites
```
{
  "projects": {
    "nycnode-denormalizer": "git@github.com:mateodelnorte/nycnode-denormalizer.git",
    "nycnode-meetup-ingestor": "git@github.com:mateodelnorte/nycnode-meetup-ingestor.git",
    "nycnode-site": "git@github.com:mateodelnorte/nycnode-site.git",
    "nycnode-user-ingestor": "git@github.com:mateodelnorte/nycnode-user-ingestor.git",
    "nycnode-youtube-ingestor": "git@github.com:mateodelnorte/nycnode-youtube-ingestor.git"
  }
}
```
try something like the following if you're making some composite library (https://github.com/mateodelnorte/meta/blob/master/.meta): 
```
{
  "ignore": [ ".git", ".vagrant", ".vscode", "node_modules" ],
  "projects": {
    "plugins/loop-things": "git@github.com:mateodelnorte/loop-things.git",
    "plugins/meta-docker": "git@github.com:mateodelnorte/meta-docker.git",
    "plugins/meta-exec": "git@github.com:mateodelnorte/meta-exec.git",
    "plugins/meta-git": "git@github.com:mateodelnorte/meta-git.git",
    "plugins/meta-init": "git@github.com:mateodelnorte/meta-init.git",
    "plugins/meta-project": "git@github.com:mateodelnorte/meta-project.git",
    "plugins/meta-npm": "git@github.com:mateodelnorte/meta-npm.git"
  }
}
```
7. if you're building a system, your next step will be `meta npm install`. if you're making a library, your next step will be `meta npm link`

**Comment by mateodelnorte** [comment]
The best way to understand meta, at the moment, is probably to clone meta and do a `meta npm link` and you'll see how the magic works. 

Clone git@github.com:mateodelnorte/meta.git then cd into it and do `./bin/meta`. Then run `./bin/meta npm link` then do `./bin/meta` and notice what changes.

**Comment by reggi** [comment]
Thanks @mateodelnorte I still feel like your skipping a step. What is used to get these repositories downloaded?

**Comment by reggi** [comment]
Once I have the `.meta` file I can run `meta npm install` but the repos arent local yet.

```
Thomass-MBP-2:test-meta thomas$ meta npm install

test-meta:
npm WARN test-meta@1.0.0 No description
npm WARN test-meta@1.0.0 No repository field.
test-meta ✓

monorepo-private@reggi:
monorepo-private@reggi exited with error: Error: spawnSync /bin/sh ENOENT

monorepo-public@reggi:
monorepo-public@reggi exited with error: Error: spawnSync /bin/sh ENOENT
```

**Comment by mateodelnorte** [comment]
`git clone [repoUrl]`. make sure you include it in the meta repo's .gitignore.

**Comment by mateodelnorte** [comment]
so, the first time you're creating a meta repo it's a little manual.  the magic comes from when the next person has to `meta git clone`. it all comes down at once for them. 

that said, for adding commands, I created https://github.com/mateodelnorte/meta-project where I'm adding commands for quickly adding child repos, etc.

**Comment by reggi** [comment]
I think I get it.`meta git clone` is a really weird idea because the expected behavior I would assume is that it would clone `loop git clone [repoUrl]` and clone the same repo many times. I guess I'm looking for `gits populate` but you skipped the step of `git clone [repoUrl] repo && cd repo && gits populate` by creating `meta git clone [repoUrl]`.

**Comment by mateodelnorte** [comment]
Delete your project. then type `meta git clone [projectRepo]` and I think you'll be happy with it. ;)

I see your point, though, that if you just pulled `master` on your meta repo and somebody else added a few child repos, then you'd like something like `meta git sync` to clone the repositories you don't already have.

**Comment by mateodelnorte** [comment]
meta now includes logic to check to see if projects exist in your .meta file which aren't cloned locally. if detected it will instruct you to run `meta git update` to clone the missing repos. 

eb0fa4c40cc777eadd6eded13772d6f3e6b288db

**Comment by reggi** [comment]
Thanks for adding `meta git update`!
