### ISSUE TITLE
How to do code sharing and CI/CD?

### ISSUE THREAD

**Issue by rvanzon** [mateodelnorte/meta#60]
Don't know if this is the place to ask. 
But I would like to know how to do code sharing. 

My project consist out of three microservices (NodeJS). I set up CI/CD on GitLab that builds the a microservice on change and pushes it into a cluster. These microservices have shared code, like database-models, policy-rules etc. 

What's the best way to set this up? I was thinking about building the meta-project, but this makes CI/CD pretty complicated I think.

Maybe checkout the repo's in the build-fase? or use npm-modules? Or maybe a meta-project in a meta-project?

Any help is welcome, thanks!

**Comment by mateodelnorte** [comment]
separate your shared code into new repositories that are just node modules you reference in your other projects. when developing, you can do `meta npm link` or `meta npm symlink` (assuming you have meta-npm installed). when you're ready to publish, you can update your package.json files in your projects to reference the names of the modules they use.

**Comment by mateodelnorte** [comment]
you can do these side by side if you like, or you can have multi-level meta projects. up to you. at my work, we have nested meta projects similar to the following: 

company-name
  lib
  firmware
  infrastructure
  services
  web

some of those meta projects have meta projects under them, as well. all of those have child repositories under them.

**Comment by mateodelnorte** [comment]
Interested in contributing a README update, or a wiki page on the topic, once you've figured it out?

**Comment by rvanzon** [comment]
Thanks for your quick response.

I thought about using `npm link`, as I actually used this structure with former projects. But the step of  altering package.json manually, I don't like. Maybe I can integrate this in the build-step. Replace symlinked package to repo-URL's.

Or maybe use the linked packages as dev-dependencies and the "live" ones in dependencies. Will try it out.

Thanks!
Yes, I am certainly interested to contribute. :)

**Comment by mateodelnorte** [comment]
Not sure what you mean. The point of npm link is that you don't have to
modify package.json. If you're trying to figure out how to use private npm
repos for private npm modules, there are ways to do that. Search for
"package.json git+ssh".

**Comment by rvanzon** [comment]
I mean that in the package.json the reference is '../../local_path', if I remember correctly, and in production it should be git+ssh. But I will test it out.

**Comment by mateodelnorte** [comment]
That's not correct. module references in package.json are almost always version numbers: https://github.com/mateodelnorte/meta/blob/master/package.json#L46. npm link will simply create a symlink in your node_modules folder to another folder on your machine, instead of directly installing the package from the web to a child directory. Read up on npm, and you'll find some useful information.

**Comment by rvanzon** [comment]
What I mean is that I though the package.json is altered by npm and replaced by the linked package, but that's not the case. So scrap that ;)
