### ISSUE TITLE
Yarn warns about package-lock.json

### ISSUE THREAD

**Issue by aleclarson** [mateodelnorte/meta#62]
While running `yarn` in a local clone:
>warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

```sh
$ yarn --version
1.12.3
```

**Comment by patrickleet** [comment]
it's developed using npm, not yarn - this is just a warning - if you want to use yarn you can but I don't think we'll be dropping npm
