### ISSUE TITLE
consider using another argv parser

### ISSUE THREAD

**Issue by aleclarson** [mateodelnorte/meta#77]
[cacjs/cac](https://github.com/cacjs/cac) is a drop-in replacement for commander made by @egoist.

What I dislike about __commander__:
- tons of unresolved issues and PRs
- its creator is no longer involved

What I like about __cac__:
- it uses `semantic-release`
- it uses Typescript
- fixes #39 (see [here](https://github.com/cacjs/cac#commandallowunknownoptions))

What gives me pause about __cac__:
- it has 46% test coverage (not very good)
- it's not as "mature"
- it doesn't have as many users (yet?)

**Comment by mateodelnorte** [comment]
Yeah, our custom commander usage is only because they took over a year to
get to merging my or. And when they did, they asked to refactor all
dependencies into local code... Which wasn't a thing when I started!

**Comment by mateodelnorte** [comment]
I chose it so that I could to git style subcommands. But it could be that
there are benefits to a monolithic command... Like the ability to do
inspection of a single process.

**Comment by aleclarson** [comment]
> git style subcommands

I think I'll open an issue about this.

**Comment by aleclarson** [comment]
Also, since you're using email. Note that I edited the OP to add "fixes #39"

**Comment by mateodelnorte** [comment]
Search for mateodelnorte. You'll see it. IIRC, it fixed git style
subcommands on Windows.

**Comment by aleclarson** [comment]
Not seeing any commits authored by you: https://github.com/tj/commander.js/search?q=author%3Amateodelnorte&unscoped_q=author%3Amateodelnorte&type=Commits

**Comment by aleclarson** [comment]
I'll just look at your fork: https://github.com/mateodelnorte/commander.js 😛

**Comment by mateodelnorte** [comment]
It's still unmerged...
https://github.com/tj/commander.js/pull/604

**Comment by mateodelnorte** [comment]
Ah yes. The biggest aspect is that it allows dependencies to add git sub
commands.

**Comment by aleclarson** [comment]
Of course it's not merged yet. :)

Good news! CAC already supports "git-like subcommands". It says so in the README! 🎉

**Comment by aleclarson** [comment]
Actually, I might have jumped the shark..

**Comment by mateodelnorte** [comment]
We'll just have to see if it supports them being applied by other modules.
If not, we can make a PR over there.

**Comment by Jcbobo** [comment]
with git-like subcommands you are considering also git flow or not? ( i.e git flow feature start featurename) at the moment  (if i understand correctly how the argument parsing is done ) the only way to support it at the moment is adding git flow support to meta-git plugin (but in my opinion should be a dedicated and optional plugin)

**Comment by mateodelnorte** [comment]
You could easily add a plugin that just adds `meta-git-flow-X` commands. It wouldn't need to be in `meta-git`.

**Comment by patrickleet** [comment]
@Jcbobo 

> with git-like subcommands you are considering also git flow or not?

this is kind of a tangent so I won't go deep into it, but I gave up git flow years ago. Git Flow multiplied by 10-20+ projects (microservices, modules, libs) is way too much mental overhead. Trunk based development with robust CD is much more preferable, imo. I know everyone has their own styles and meta should support any workflow you'd like, but I really do not miss git flow haha.

**Comment by Jcbobo** [comment]
Different situation required different development flow ( at least should)
i'm non a fan of git flow but is working at the moment but a generic
multi-repo coordination  tool should support more options as possible.
My concern were related to match the git [command] respect to git flow
[command]  to select the plug-in


Il giorno Mer 2 Gen 2019, 20:44 Patrick Scott <notifications@github.com> ha
scritto:

**Comment by patrickleet** [comment]
Yes, like I said - it should support any workflow.

So your concern is how a `git flow` plugin should work given that they are piggy backing on git as well

```
git flow init -d
git flow feature start <your feature>
```

Because

```
meta git flow
```

Would be picked up by `meta-git` ?

**Comment by Jcbobo** [comment]
about how plugins with "similar" command are disambiguate

**Comment by Jcbobo** [comment]
as supposed creating a plugin with name git flow, and command 

> Yes, like I said - it should support any workflow.
> 
> So your concern is how a `git flow` plugin should work given that they are piggy backing on git as well
> 
> ```
> git flow init -d
> git flow feature start <your feature>
> ```
> Because
> 
> ```
> meta git flow
> ```
> Would be picked up by `meta-git` ?

is exacly what i noticed trying to implement the git flow plugin

**Comment by aleclarson** [comment]
Bump. I still think this would be a good move forward.

**Comment by aleclarson** [comment]
I've been using another commander-like parser recently called ["sade"](https://github.com/lukeed/sade). I haven't had time to compare it with "cac", but it's almost half the size.

**Comment by mateodelnorte** [comment]
This looks very commander-like. I don't see coverage for git-style subcommands, though. And that's really the main feature we get from commander, other than ability to specify commands and options.
