### ISSUE TITLE
create robust, attractive docs

### ISSUE THREAD

**Issue by aleclarson** [mateodelnorte/meta#79]
The readme feels very bloated because of the huge asciicinema.org images. We should convert them to `.gif` images to fix this, and we can still link to asciicinema.org if you want.

To avoid overwhelming new users, it may be worth moving most of the examples to the Wiki, but that's up to you.

**Comment by mateodelnorte** [comment]
I'd like to completely redo the docs with something that looks more
professional.

**Comment by aleclarson** [comment]
Great! The ideal solution is getting Github pages going so we can have a fancy documentation website!

**Comment by patrickleet** [comment]
gitbook is pretty nice for that

**Comment by aleclarson** [comment]
I highly recommend https://docusaurus.io which is what Babel, Jest, etc use.

**Comment by mateodelnorte** [comment]
@kaveet

**Comment by mateodelnorte** [comment]
https://docusaurus.io looks pretty great. Here are a few example docs sites I think are great, and we could emulate: 

- https://gulpjs.com/docs/en/getting-started/quick-start
- https://jestjs.io/docs/en/getting-started
- https://renovatebot.com/docs/

Anyone else have a style they want to point out?

**Comment by dee-me-tree-or-love** [comment]
Is anyone still interested in this issue? I would like to offer some help in writing the docs
