### ISSUE TITLE
Checkout after adding a project

### ISSUE THREAD

**Issue by vmx** [mateodelnorte/meta#87]
To me the workflow after adding a project that has already a history is not clear.

Here's what I did:

```console
$ meta project add js-multihash git@github.com:multiformats/js-multihash.git
meta project adding 'git@github.com:multiformats/js-multihash.git' at js-multihash
created /home/vmx/src/pl/meta/ipld/js-multihash
Initialized empty Git repository in /home/vmx/src/pl/meta/ipld/js-multihash/.git/
set remote origin to git@github.com:multiformats/js-multihash.git
adding "js-multihash": "git@github.com:multiformats/js-multihash.git" to .meta file at /home/vmx/src/pl/meta/ipld/.meta
adding js-multihash to .gitignore at /home/vmx/src/pl/meta/ipld/.gitignore
```

`js-multihash` isn't checked out yet:

```console
$ ls -a js-multihash
.  ..  .git
```

So I though I do a `meta git update`:

```console
$ meta git update
all repositories in .meta are cloned locally
```

That doesn't do anything. Next try is a `pull` (that would also screw with your existing repos):

```console
$ meta git pull 
…
here is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
```

A checkout would make more sense:

```console
$ meta git checkout
js-multihash:
fatal: You are on a branch yet to be born
js-multihash: command 'git checkout ' exited with error: Error: Command failed: git checkout
```

There's still no proper checkout.

Next is then just removing the directory and using `update`:

```console
$ rm -Rf ./js-multihash
$ meta git update

*** the following repositories have been added to .meta but are not currently cloned locally:
*** { 'js-multihash': 'git@github.com:multiformats/js-multihash.git' }
*** type 'meta git update' to correct.


 cloning missing repositories


js-multihash:
Cloning into 'js-multihash'...
remote: Enumerating objects: 7196, done.
remote: Total 7196 (delta 0), reused 0 (delta 0), pack-reused 7196
Receiving objects: 100% (7196/7196), 6.11 MiB | 5.40 MiB/s, done.
Resolving deltas: 100% (1373/1373), done.
js-multihash
```

That does the actual checkout as I would expect it.

So it is expected that `meta project add` is about new projects and not existing ones.

**Comment by mateodelnorte** [comment]
That's correct. For an existing project, you can just cd into the created
directory and to a git pull origin master.

**Comment by patrickleet** [comment]
`meta git pull origin master` should do it too

once you set an upstream on your repo `meta git pull` should work

you can add the `-u` flag the first time you push

```
git push -u origin master
```

Or run the command that the warning told you to run:

```
 git branch --set-upstream-to=origin/<branch> master
```

**Comment by vmx** [comment]
@patrickleet The `git pull` would also pull all other existing repos.

I guess my main concern is consistency. I don't see an issue, that it doesn't pull the default branch automatically (although I'd prefer that). But then it's strange that `meta project add` does initialize an empty repository.

I'm new to the project and just want bring up my first impressions as I personally find it valuable if someone with a fresh look contributes their pain points as they are different from being used to a system :)

**Comment by patrickleet** [comment]
@vmx it doesn't know what the "default" branch is as one had never been set. That's what the upstream setting is for which hadn't been configured before. This warning is from git, not meta. Just want to make sure we're on the same page about that. All `meta git *` is doing is running `git *` in each folder.

If you definitely wanted all of the upstreams for your project to be set to origin/master you could run

```
meta exec "git branch --set-upstream-to=origin/master master"
```

I'm not sure meta wants to make assumptions about settings that could be different for every project.

I believe all `meta project add` does is:
1) add project to .meta file
2) add it to .gitignore
3) create a folder, git init, and set the remote

@mateodelnorte sound right?

Even when you create a brand new project on github you need to set an upstream (notice `git push -u`

![image](https://user-images.githubusercontent.com/474827/50170325-aca3c800-02bd-11e9-8731-640fa2fa2128.png)

If your issue is addressed, may I close this issue? Or are we still disconnected on something?

**Comment by mateodelnorte** [comment]
Correct @patrickleet. Meta trusts that the remote you tell it about exists. And `meta project add x y` only cares about setting up the bare minimum to get you working. Your meta and child repos could be in any number of states, on master, all on a feature branch, or on multiple branches. So, it doesn't make assumptions about what to check out for the new repo.

**Comment by vmx** [comment]
@patrickleet, @mateodelnorte: Thanks for being so nice/friendly to me. I'm knpo how git works and that those `meta git` operations just do normal git things on every repo. My goal for this issue is to make `meta` nice to use for the case where you want to use it for existing repositories.

> (@patrickleet) @vmx it doesn't know what the "default" branch is as one had never been set. That's what the upstream setting is for which hadn't been configured before

My point is that `meta git update` does exactly what I'd expect it to do. If there are no directories yet, it checks out the default branch of those repos defiend in `.meta`.

> (@mateodelnorte) So, it doesn't make assumptions about what to check out for the new repo.

It makes the assumption that I'd like to have an empty initilaized repo.

Perhaps it makes things clearer which flow I'd propose. I just make up options, it doesn't matter if they are named like that, or if they become subcommands instead, it's just about the general idea:

### Use case: I want to add a repo with existing code:

```
// This just adds the project to `.meta`
meta project add x y
// Checks the newly added project out as I'd expect it
meta git update
```

### Use case: I want to add a brand new repo without any code in there yet

```
// This just adds the project to `.meta`
meta project add --init x y
```

PS: I fear a bit that I don't find the right words and come across a noob that doesn't understand how `meta` works and wants to change it to a thing that it not really is. So please read all my comments in a friendly tone and as suggestions to make it better in case it aligns with the overall goal :)

**Comment by mateodelnorte** [comment]
Hey @vmx. No worries. I think we get your perspective clearly. No assumptions over here that you're junior. 

I'm hesitant to do a `meta git update` as a component command of `meta project add x y` because it will potentially cause additional repos to be pulled and synced. It's a little pedantic, but a dev could know that there are large amounts of new code that they're not ready to pull down yet. Sometimes you just want to do the one, atomic, operation you're concerned with. It could be quite surprising that doing a `project add` ends up syncing your code. You might just not be in a position to deal with the mental overhead of worrying about what just came down. 

I would, however, entertain the idea of having something like a `meta git update --include-only [name of new repo]` such that only the new repo's code gets pulled. I'm fairly certain [`meta git update`](https://github.com/mateodelnorte/meta-git/blob/master/lib/metaGitUpdate.js) would have to be updated to allow that.

**Comment by mateodelnorte** [comment]
What are you proposing?

**Comment by vmx** [comment]
I see the two use-cases mentioned in https://github.com/mateodelnorte/meta/issues/87#issuecomment-448573255.

I'm unsure if they both should be achievable with a single command, that would then e.g. be:

```
// current behaviour
meta project init x y
// npm git update-like behaviour
meta project import x y
```

Or if it should be an option:
```
// current behaviour
meta project add --init x y 

// npm git update-like behaviour
meta project add x y // this doesn't create any directories
meta git update
```

**Comment by aleclarson** [comment]
I think @vmx and I both have the same concerns. See here: https://github.com/mateodelnorte/meta-project/pull/10

**Comment by throskam** [comment]
I completely agree with @vmx, I was really confused when I found an empty directory after adding an existing repository to the meta project. 

I did almost exactly the same mental gymnastics to make it work. I was also surprise that my use case wasn't documented and thought I was using the tool wrong (even if the logs were clear when I looked back at them).

Maybe I'm missing something here, but why does meta initialize an empty repository and does not simply clone it ? 
As a first time user, I would expect `meta project add x y` to basically do `git clone y x`, `meta project add --init x {y}` to create an empty repository inside `x` with the remote `y` optionally set.

Anyways, after that rocky start, the rest of my experience was pretty smooth :)

**Comment by mateodelnorte** [comment]
I'm not against renaming the current add command to `meta project init` and creating a new `meta project add` which expects a remote to exist.

**Comment by drusellers** [comment]
> I completely agree with @vmx, I was really confused when I found an empty directory after adding an existing repository to the meta project.

Ditto, it took me a hot minute to realize what was going on.

**Comment by nwillc** [comment]
It confused my that the meta git pull failed after the project add, but worked if I did a fresh meta clone of same repo elsewhere...

**Comment by patrickleet** [comment]
this was cleaned up in https://github.com/mateodelnorte/meta-project/pull/25 

There is now `meta project import` for cloning existing repos and `meta project create` for initializing new ones
