### ISSUE TITLE
Move to an org

### ISSUE THREAD

**Issue by aleclarson** [mateodelnorte/meta#91]
There's already an NPM org named `meta`. Do you own that, @mateodelnorte?

Also, the Github username is taken. 😢 

Maybe `@metapkg` would be good enough?

**Comment by mateodelnorte** [comment]
It would be great if we could convince https://github.com/meta, from the bottom of his heart, to donate his username to be our new org name. Otherwise, maybe something like `getmeta` (I went ahead and secure [getmeta](https://github.com/getmeta)).

**Comment by aleclarson** [comment]
I opened an issue [here](http://bit.ly/2rIYXJc). Hopefully he/she responds. 🤞

**Comment by mateodelnorte** [comment]
I've also emailed github support. As a side note, I also emailed to see if we can get the servicebus and sourced usernames to use as orgs for those projects.

**Comment by aleclarson** [comment]
The @meta user deleted that repository, so it looks like they're committed to keeping their username. :P
